README.md
I <3 Gitlens! Thanks for making it. I hope one day to make a more substantial donation to the project, but for now I offer this small donation name typo fix. :)
=> Fix typo Bronse->Bronze

src/ui/settings/index.html
=> "invididually" -> "individually"

package.json
it's the same as #548 for ansible language
=> Make ansible use document scope

src/views/nodes/branchNode.ts
Please refer to [this](https://github.com/eamodio/vscode-gitlens/issues/951) for reference of the issue.
=> Fixes #951 - Starring branch updates view properly

package.json
Adds welcome and settings command to extension context menu.
=> Closes #952 & #953 - Adds welcome and settings in extension context menu

src/commands/git/branch.ts, src/commands/git/tag.ts
=> Fixes typo forcably -> forcibly

README.md
---
Adds to the README a section which details how to configure git config such that the gitlens interactive rebase will work.
=> Adds instructions to set VS Code as default git editor in order to use interactive rebase

src/annotations/blameAnnotationProvider.ts
Check the URI of documents to provide hovers. Close #1587.
=> Check the URI of documents to provide hovers. Close #1587.

src/system/path.ts
=> Fixes #1928 quiet when editing root folder files

src/commands/gitCommands.actions.ts, src/views/viewCommands.ts
"Are **your** sure you want..." -> "Are **you** sure you want..."
=> Fixes grammatical mistake

CHANGELOG.md
Fix typos and duplicated words in CHANGELOG.md
=> Fix typos and duplicated words in CHANGELOG.md

CONTRIBUTING.md
Fix wording in CONTRIBUTING.md
=> Fix wording in CONTRIBUTING.md

src/webviews/apps/plus/graph/GraphWrapper.tsx
- Implemented `onColumnResized` and `columnsSettings` input properties of the `GraphContainer` to use GitLens `onColumnChange` event and `GraphConfig` state.
[GITLENS-260](https://gitkraken.atlassian.net/browse/GITLENS-260)
=> GITLENS-260 - Save column width settings on exit and restore when the graph is opened again in GitLens webview

CHANGELOG.md, src/views/nodes/compareBranchNode.ts, src/views/nodes/compareResultsNode.ts, src/views/nodes/resultsFilesNode.ts
Shows git diff shortstat in comparison e.g. 7 files changed with 58 additions and 29 deletions.
Closes #2078
=> Closes #2078 - Shows diff shortstat in comparison

README.md
Fix typo in README in an https link.
=> Closes #2121 - Fix typo in README

src/plus/webviews/graph/graphWebview.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/plus/graph/tsconfig.json
Gitlens changes to coincide with component updates: https://github.com/gitkraken/GitKrakenComponents/pull/37
=> Updates graph component package paths

src/webviews/apps/plus/graph/GraphWrapper.tsx
Create and pass a function to the graph that will render the icons.
required for https://github.com/gitkraken/GitKrakenComponents/pull/33
=> GITLENS-257 provide graph with icon library

package.json, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, yarn.lock
Fixing leftover issues from the initial graph icons PR.
Note that this PR will be dependent on a version bump in the graph-component library as a result of this PR: https://github.com/gitkraken/GitKrakenComponents/pull/44
=> Update graph Icons

src/webviews/apps/plus/graph/GraphWrapper.tsx
Retrieves platform and translate it into one of the expected platforms for the container.
Note: tested on a windows machine, will need to be tested on a Mac prior to approval
https://gitkraken.atlassian.net/browse/GITLENS-289
=> Send platform to the graph

src/webviews/apps/plus/graph/graph.scss
- There is also some UI jumping when you check/uncheck a column
- Modified CSS class `column-combo__item` and `column-combo__item-check`.
https://github.com/gitkraken/GitKrakenComponents/issues/79
=> 79 - UI jumping when you check/uncheck a column

package.json, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/theme.ts, yarn.lock
This PR sends over the graph colors needed for the following PR to work: https://github.com/gitkraken/GitKrakenComponents/pull/97
Note that after merging the component-side PR, the library version should be bumped to see the changes.
=> Send theme colors for selected and hovered rows

src/env/node/git/localGitProvider.ts, src/git/models/graph.ts, src/plus/github/githubGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/storage.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/components/menu/index.ts, src/webviews/apps/shared/components/menu/menu-divider.ts, src/webviews/apps/shared/components/menu/menu-item.ts, src/webviews/apps/shared/components/menu/menu-label.ts, src/webviews/apps/shared/components/menu/react.tsx, src/webviews/apps/shared/components/overlays/pop-menu/pop-menu.ts, src/webviews/apps/shared/components/search/search-input.ts
This is just a demo hack to use the `includeRefsById` feature in https://github.com/gitkraken/GitKrakenComponents/pull/156
/cc @gitkraken/gitlens-devs
=> (wip) hack to demo "include" filtering in Graph

package.json, src/config.ts, src/env/node/git/localGitProvider.ts, src/plus/github/githubGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/settings/partials/commit-graph.html, yarn.lock
Adds colors and settings to support displaying a rich scrollbar on the graph.
Component-side PR here: https://github.com/gitkraken/GitKrakenComponents/pull/194
**Note:** currently sends hard-coded color values (we will need to determine which colors to use and base them on theming before the PR becomes official).
**Note 2:** the component-side PR must be merged first, and version bumped in this branch, before this PR becomes official.
=> Graph: add rich scrollbar support

package.json, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, yarn.lock
This coincides with updates to Graph declarations. Will need a new version of the `GitkrakenComponents` with the latest exports and d.ts files.
=> Updates graph typings and constants

src/plus/subscription/subscriptionService.ts
=> Fixes issue w/ preview trial "winning" over paid

src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Provides support for the `path` query parameter in deep links which provides a path to the repo on disk.
Note: while implementing this I noticed that deep links currently aren't working when the graph is in a view, since  the "open in commit graph" command seems to be no-oping. This is a regression (the command used to work even when the graph was in a view) and should be fixed in a separate task.
=> Support deep links that provide repo path

src/webviews/apps/settings/partials/blame.html, src/webviews/apps/settings/partials/changes.html, src/webviews/apps/settings/partials/code-lens.html, src/webviews/apps/settings/partials/commit-graph.html, src/webviews/apps/settings/partials/current-line.html, src/webviews/apps/settings/partials/heatmap.html, src/webviews/apps/settings/partials/hovers.html, src/webviews/apps/settings/partials/modes.html, src/webviews/apps/settings/partials/rebase-editor.html, src/webviews/apps/settings/partials/status-bar.html, src/webviews/apps/settings/partials/terminal-links.html, src/webviews/apps/settings/partials/views.branches.html, src/webviews/apps/settings/partials/views.commitDetails.html, src/webviews/apps/settings/partials/views.commits.html, src/webviews/apps/settings/partials/views.contributors.html, src/webviews/apps/settings/partials/views.file-history.html, src/webviews/apps/settings/partials/views.line-history.html, src/webviews/apps/settings/partials/views.remotes.html, src/webviews/apps/settings/partials/views.repositories.html, src/webviews/apps/settings/partials/views.searchAndCompare.html, src/webviews/apps/settings/partials/views.stashes.html, src/webviews/apps/settings/partials/views.tags.html, src/webviews/apps/settings/partials/views.worktrees.html, src/webviews/apps/settings/settings.html
Updates the info links from the old readme sections to the new help center docs.
=> Remaps links in settings to Help Center sections

package.json, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, yarn.lock
This PR fixes following problems related with the fix of visual glitches produced by `Electron 22`:
- Fixed problem with graph scrollbar color and themes 
- See for details: https://github.com/gitkraken/GitKrakenComponents/pull/229#issuecomment-1612355902
- Fixed problem with default `VSCode` `-webkit-scrollbar` css value and the graph
- See for details: https://github.com/gitkraken/GitKrakenComponents/pull/229#issuecomment-1612360283
- This task works with following PR: https://github.com/gitkraken/GitKrakenComponents/pull/229
- This PR should be merge after this one https://github.com/gitkraken/GitKrakenComponents/pull/229
and we will need to update the `@gitkraken/gitkraken-components` package dependency as well to use latest version. 
Internal JIRA task: `GK.3814`
Github task: …
=> GK graph has some visual glitches

README.md
Fixes #2793
These are the changes requested for my username to be updated on the contributors list.
=> Fixes #2793 changes to update readme to new username

CHANGELOG.md, README.md
#2785
---
Updated URL of the remote provider integration doc
=> Updates url for remote provider integration doc

package.json, src/webviews/apps/plus/graph/GraphWrapper.tsx, yarn.lock
- [GK-4117](https://gitkraken.atlassian.net/browse/GK-4117)
- Added input property to disable show/hide branches button from the ref node in GKC.
- Updated graph dependency version.
=> Add input prop to enable show and hide refs options

src/git/parsers/diffParser.ts
The `while` statement may cause index overflow problems in logic.
=> Fixes code logic issues

src/commands/remoteProviders.ts, src/constants.ts, src/git/gitProviderService.ts, src/git/models/repository.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providerIntegration.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/plus/webviews/focus/focusWebview.ts, src/system/iterable.ts
Fixes possible auth issues with self-hosted integrations
=> Ensures split between hosted/self-hosted integrations

package.json, src/constants.ts, src/container.ts, src/plus/drafts/draftsService.ts, src/plus/gk/account/organization.ts, src/plus/gk/account/organizationService.ts, src/plus/webviews/patchDetails/patchDetailsWebview.ts, src/plus/webviews/patchDetails/protocol.ts, src/webviews/apps/commitDetails/components/commit-details-app.ts, src/webviews/apps/commitDetails/components/gl-commit-details.ts, src/webviews/apps/commitDetails/components/gl-wip-details.ts, src/webviews/apps/home/home.html, src/webviews/apps/home/home.ts, src/webviews/apps/plus/patchDetails/components/gl-draft-details.ts, src/webviews/apps/plus/patchDetails/components/gl-patch-create.ts, src/webviews/apps/shared/components/button.ts, src/webviews/apps/welcome/welcome.html, src/webviews/apps/welcome/welcome.scss, src/webviews/apps/welcome/welcome.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/commitDetails/protocol.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts, src/webviews/welcome/protocol.ts, src/webviews/welcome/welcomeWebview.ts
Resolves [GLVSC-375] [GLVSC-376] [GLVSC-387] 
[GLVSC-375]: https://gitkraken.atlassian.net/browse/GLVSC-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GLVSC-376]: https://gitkraken.atlassian.net/browse/GLVSC-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GLVSC-387]: https://gitkraken.atlassian.net/browse/GLVSC-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds org-level settings 

README.md, package.json
Fix typos in README.md and package.json.
To correct a minor typo, I have not updated CHANGELOG.md.
The issue corresponding to this pull request is #3116.
=> Fixes #3116 - Fix typos in README.md and package.json

CHANGELOG.md, src/webviews/apps/commitDetails/components/gl-commit-details.ts, src/webviews/apps/shared/components/commit/commit-identity.ts, src/webviews/apps/shared/components/formatted-date.ts, src/webviews/apps/shared/components/rich/issue-pull-request.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/commitDetails/protocol.ts
=> Closes #3153 adds defaultDateStyle preference to commit details

CHANGELOG.md, src/gk/models/drafts.ts, src/views/draftsView.ts
- introduces a new draft type: `suggested_pr_change`
- groups drafts of the new type under a new title: "Suggested Changes"
=> GLVSC-420 Groups suggested PR changes under "Suggested Changes" section

README.md, package.json, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/webviews/focus/registration.ts, src/webviews/apps/home/home.html, src/webviews/apps/plus/focus/components/focus-app.ts, src/webviews/apps/welcome/welcome.html
Updates user-facing strings to Launchpad.
Updates icon to rocket.
Note: Does not update any internal naming - this should be done in separate work, and telemetry events/command naming should be carefully reviewed.
=> Updates Focus UI strings

CHANGELOG.md, src/constants.ts, src/git/queryResults.ts, src/views/draftsView.ts, src/views/nodes/abstract/viewNode.ts, src/views/nodes/draftNode.ts, src/views/nodes/pullRequestNode.ts, src/views/nodes/resultsSuggestedChangeNode.ts, src/views/nodes/resultsSuggestedChangesNode.ts, src/views/viewCommands.ts
Shows a PR’s suggested changes anywhere we currently display a PR node in our GitLens views (Commits, Branches, Remotes).
=> Includes suggested changes to Pull Request Nodes (GLVSC-425)

src/constants.ts, src/git/gitProviderService.ts
Completes GLVSC-463
https://gitkraken.atlassian.net/browse/GLVSC-463
=> Stops sending 'providers/changed' event

package.json, src/ai/aiProviderService.ts, src/ai/anthropicProvider.ts, src/ai/geminiProvider.ts, src/ai/openaiProvider.ts, src/ai/prompts.ts, src/ai/vscodeProvider.ts, src/config.ts, src/plus/webviews/patchDetails/patchDetailsWebview.ts, src/plus/webviews/patchDetails/protocol.ts, src/webviews/apps/commitDetails/components/commit-details-app.ts, src/webviews/apps/commitDetails/components/gl-inspect-patch.ts, src/webviews/apps/commitDetails/components/gl-wip-details.ts, src/webviews/apps/plus/patchDetails/components/gl-patch-create.ts, src/webviews/apps/plus/patchDetails/components/patch-details-app.ts, src/webviews/apps/plus/patchDetails/patchDetails.scss, src/webviews/apps/plus/patchDetails/patchDetails.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/commitDetails/protocol.ts
Adds a sparkle action to the title input of Cloud Patches and Code Suggestions.
=> Adds AI message generation for Cloud Patches and Code Suggestions

CHANGELOG.md, src/constants.ts, src/container.ts, src/plus/drafts/draftsService.ts, src/plus/focus/focus.ts, src/plus/focus/focusProvider.ts, src/plus/gk/account/authenticationConnection.ts, src/plus/gk/account/subscriptionService.ts, src/plus/gk/serverConnection.ts, src/plus/integrations/integrationService.ts
=> Replaces "Open in Editor" link in Launchpad with a link to gk.dev [GLVSC-504]

.vscodeignore, docs/links.md
Adds documentation describing the deep link types supported by GitLens.
=> Adds deep link documentation

src/git/models/reference.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/components/button.react.tsx, src/webviews/apps/shared/components/button.ts, src/webviews/apps/shared/components/code-icon.react.tsx, src/webviews/apps/shared/components/code-icon.ts
Click jumps to HEAD, Alt+Click opens a ref picker to jump to the chosen ref.
=> Adds a jump to ref button to the graph

src/env/node/git/localGitProvider.ts
https://github.com/user-attachments/assets/35fab657-0f75-402e-b973-e61f5ad39b84
=> Adds stash commit message to commit graph row

CHANGELOG.md, src/webviews/apps/home/home.html, src/webviews/apps/home/home.scss, src/webviews/apps/home/home.ts
Adds handler for click on expandable area
=> Fixes Clicking anywhere on "Get started" should expand the section #3386 (GLVSC-602)

CHANGELOG.md, src/commands/gitCommands.ts, src/commands/quickCommand.buttons.ts, src/commands/quickCommand.ts, src/constants.ts, src/plus/focus/focus.ts, src/plus/focus/focusProvider.ts
=> Launchpad: upgrade authentication invitation GLVSC-582

package.json
Fixes Worktrees typo in package.json: `Workrees` -> `Worktrees`
Closes #3406
=> Fixes worktrees typo - closes #3406

CHANGELOG.md, package.json, src/commands/patches.ts, src/git/utils/commit-utils.ts, src/plus/webviews/graph/graphWebview.ts, src/system/commitUtils.ts
https://github.com/user-attachments/assets/edde9171-d3e6-442f-bc06-fd98e5d0270f
=> Provides commit title and description from stash on create patch from stash action

CHANGELOG.md, src/telemetry/usageTracker.ts
=> Fixes UsageTracker first track

src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts
Fixes GitLab items failing to load into Launchpad, and possibly fixes issues with Jira integration as well.
=> Uses custom fetch for shared provider api requests

src/container.ts, src/env/browser/providers.ts, src/env/node/providers.ts, src/plus/integrations/authentication/github.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/githubGitProvider.ts
=> Move remaining GitHub auth logic that uses vscode auth (GLVSC-589)

src/plus/integrations/providers/github/githubGitProvider.ts
=> Uses silent=false in web environments (GLVSC-621)

CHANGELOG.md, src/plus/gk/account/subscriptionService.ts
Provides correct value to setProFeaturesVisibility
=> Fixes plus features flag toggling

CHANGELOG.md, src/webviews/apps/plus/graph/hover/graphHover.ts
=> Fixes Tooltip flickering #3479

src/webviews/apps/plus/graph/graph.scss
don't override position of the tooltip
=> Fixes broken ref icon tooltip

README.md
Updates the README.md to include a message explaining when Launchpad will be out of preview, with a link to upgrade to Pro at a discounted rate. Closes #3600
=> Closes #3600 - Updates README.md to include Launchpad preview message 

README.md
Update promotional message on readme.md to include new end date.
=> Update promo message end date

src/git/gitProviderService.ts, src/plus/repos/repositoryIdentityService.ts
=> Adds discovered/found repos to local path map

tsconfig.test.json
=> Removes unused fields from tsconfig.test

docs/telemetry-events.md
I've passed the code through `npm run pretty`. Here are changes that were applied to `telemetry-events.md`
=> Fixes telemetry-events.md to satisfy prettier

CHANGELOG.md, package.json, pnpm-lock.yaml
=> Updates cheerio version to fix html entities escaping

README.md
Update Launchpad: Preview to Pro wording
=> Launchpad Pro Update

CHANGELOG.md, src/webviews/apps/rebase/rebase.scss
=> Fixes invisible dropdown in the rebase view

CHANGELOG.md
=> Mentions the Start Work feature in the changelog (#3621)

README.md
- Update README with Community messaging
- Remove FAQ, since all questions are answered in the new Community vs. Pro section
=> update readme with GL Community Edition Messaging.

package.json, walkthroughs/welcome/accelerate-pr-reviews.md, walkthroughs/welcome/get-started-community.md, walkthroughs/welcome/improve-workflows-with-integrations.md, walkthroughs/welcome/streamline-collaboration.md, walkthroughs/welcome/visualize-code-history.md
Update messaging in walkthrough for v16 based on [these revisions](https://www.figma.com/design/ZRm91LPm0zpyfLwM1wwMZZ/GitLens-Onboarding-and-GL-16?node-id=3335-914&t=JlKlIhbrjxXUTRj8-4).
=> Refines walkthrough content for clarity

src/plus/startWork/startWork.ts
=> Add hover tooltip on an issue item in Start Work by extending `details`

package.json, pnpm-lock.yaml, src/plus/integrations/providers/utils.ts
=> Updates @gitkraken/provider-apis to 0.25.2

src/webviews/apps/home/components/ama-banner.ts, src/webviews/apps/home/home.ts, src/webviews/apps/shared/components/card/card.css.ts, src/webviews/apps/shared/components/card/card.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
=> Adds AMA banner to home

src/commands/generateCommitMessage.ts
=> Ensures passing scm repo context for Generate Commit Message

docs/telemetry-events.md, src/constants.telemetry.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-card.ts, src/webviews/apps/plus/home/components/merge-target-status.ts
=> Adds merge target message for community

CHANGELOG.md, README.md, src/plus/integrations/providers/azure/azure.ts, src/plus/integrations/providers/azure/models.ts
It fixes #4207.
This is a follow-up after the user's PR #4210 , because it needs some fixes
=> Fixes #4207 - Incorrect PR Link Across Azure DevOps Projects

README.md, src/plus/integrations/providers/utils.ts, src/system/-webview/__tests__/path.test.ts, src/system/-webview/path.ts
---
remove unused import & redundant jump
=> refactor: remove unused import & redundant jump

src/webviews/plus/graph/graphWebview.ts
A follow-up fix for #4498 : https://github.com/gitkraken/vscode-gitlens/issues/4498#issuecomment-3200787302
=> Fixes commands to change or set branch upstream in graph

ThirdPartyNotices.txt, package.json, pnpm-lock.yaml, src/webviews/apps/shared/components/actions/action-item.ts, src/webviews/apps/shared/components/actions/action-nav.ts, src/webviews/apps/shared/components/tree/tree-generator.ts, src/webviews/apps/shared/components/tree/tree-item.ts, src/webviews/apps/shared/components/tree/tree.css.ts
Replaces the existing tree component with a virtualized implementation using `@lit-labs/virtualizer`, significantly improving performance for large datasets while adding comprehensive keyboard navigation and accessibility features.
- Implements virtualization to handle large tree structures efficiently
- Reduces DOM overhead by only rendering visible items
- Adds optimized O(1) lookups using path-to-index and node maps
- Adds full arrow key navigation (up/down for movement, left/right for expand/collapse)
- Implements Home/End keys for quick navigation to first/last items
- Supports Enter/Space for item activation
- Includes type-ahead search functionality for quick item location
- Implements proper Tab navigation between tree items and action buttons
- Adds container-focused approach …
=> Adds virtualized tree with enhanced keyboard navigation
