gitkraken/vscode-gitlens

package.json, src/commands/showStashList.ts, src/extension.ts, src/views/gitStashExplorer.ts, src/views/repositoryNode.ts, src/views/stashExplorer.ts
Move stash explorer out of Gitlens explorer.
=> extract stash explorer

src/git/gitUri.ts
As discussed, this should be ok for Insiders and Stable and accommodate for our URI changes.
=> mixin state of super type

src/git/remotes/gitlab.ts
It seems GitLab uses a slightly-different syntax for multi-line selection, this fixes the gitlab provider to Do The Right Thing™
=> Fix GitLab integration's multi-line selection.

package.json, src/commands.ts, src/commands/common.ts, src/commands/externalDiff.ts, src/extension.ts, src/git/git.ts, src/git/models/status.ts, src/git/parsers/statusParser.ts, src/gitService.ts
Adds an "External Diff" command to launch the configured git difftool for various selections of files:
- Run command directly: All modified files
- "Staged Changes" or "Changes" group context menu: All modified files in that group
- Source Control file context menu: The selected files
Can handle a file having both staged and unstaged changes - only the selected diff (or two diffs - one for each file if both are selected) will be shown.
=> Add "external diff" command to SCM groups and files

src/annotations/annotations.ts
Only show the `Open in Remote` and `Show Commit Details` when the change is committed.
Only show a diff message when there is a previous version available.
Achieved by: 
- The removal of the `Open in Remote` and `Show Commit Details` commands for uncomitted changes.
Clicking the left one tells you that the commit couldn't be found.
Clicking the right one links you to a 404 page as `0000000000000000000000000000000000000000` is not a valid hash.
- The removal of the diff message when there is no previous commit available (e.g. the line was never changed after comitting the file).
The previous commit hash is displayed as `undefined` and clicking it is the same as clicking the right one.
Clicking on Changes errors out as there is no old hash to compare.
The diff is also not quite right, it …
=> Only show remote and details command and diff message where applicable

src/git/remotes/provider.ts
hey, thx for this awesome plugin ❤️  
we have a gitlab instance running without https -> don't ask!
here is the required change to support the http protocol (and keep the default `https`; works for all remotes) 
config sample:
```
{
"gitlens.remotes": [{ "domain": "gitlab.xxxx.at", "type": "GitLab", "protocol": "http" }]
}
```
let me know if there is something to change/adapt.
=> support for non https remotes

src/annotations/blameAnnotationProvider.ts
Added small fix to invert git blame line highlighting. When you select the line GitLens highlights all commits except that which you selected. I'm just inverted this.
=> Tuned blame line highlighting

package.json, src/commands.ts, src/commands/common.ts, src/commands/diffHeadWithBranch.ts
Hi 👋 
First thank you for your awesome plugin, I felt in love with it ❤️ 
However, these days something tickled me a little bit. I thought the workflow to compare HEAD with another branch (like comparing feature branches with master for checking colleagues Pull Requests) was a bit unfriendly (especially for people without the GitLens panel in explorer) 😅 
I thought something like _Cmd + P > Compare HEAD with ... (master)_ would be very cool.
You already made that but to use yours we need to have an external difftool configured 😢 
That's sad because you already made one awesome difftool included in Code to compare branches : I name it : "GitLens result panel".
That's it ! Just have to mix **Command Palette** and **GitLens result panel** to have an awesome workflow. 
I tried to cook …
=> Add new command to diff HEAD with branch using command palette

src/git/git.ts
The following error also caused blame not working:
> git rev-parse --symbolic-full-name my_branch@{u}
fatal: upstream branch 'refs/heads/my_branch' not stored as a remote-tracking branch
Git version: 2.17.1
=> add another unknownRevision error to detect

README.md, package-lock.json, package.json, src/commands/copyMessageToClipboard.ts, src/commands/copyShaToClipboard.ts
I replaced [copy-paste](https://github.com/xavi-/node-copy-paste) by [clipboardy](https://github.com/sindresorhus/clipboardy).
>It is more actively maintained and it fixes many of that module's issues.
https://stackoverflow.com/a/43153941/2787235
Ref #35
=> Support Linux without requiring external dependency (xclip)

src/git/git.ts
- add "-c color.branch=never" option to git branch commands, definitively disabling color branch output
.# Discussion
Branch names are mis-parsed if `git branch` output is colored (eg, when git is configured
with "config.branch=always"). Using the base "-c color.branch=never" option overrides any
user configuration, displaying git branch output as uncolored in all cases and fixing the
issue.
Notably, option ordering is important in this instance. The "-c ..." option is a git
base option, not a git branch subcommand option. So, as done here, it must be inserted
before the "branch" subcommand.
ref: Issue #415
=> Fixes #415 - branch names mangled by color escapes

package.json, src/annotations/annotations.ts, src/ui/config.ts
This setting allows disabling/enabling showing avatars in hovers. We already have settings for the explorer and blame gutter, so it makes sense to also have one for the hovers.
=> Add the gitlens.hovers.avatars configuration option

package.json
Double hyphen is a poor em dash replacement in the monospace font. `--` were replaced with `—` in the configuration properties descriptions.
=> Replace `--` with `—` in package.json

src/git/git.ts, src/git/parsers/blameParser.ts, src/git/parsers/logParser.ts, src/gitService.ts
=> Fix incorrect author display `You`(#457)

package.json
Hi. I'm a PM on Azure Pipelines. One of the features we've just shipped is an [extension for VS Code](https://github.com/Microsoft/azure-pipelines-vscode) to make it easier to author in our YAML-based format. For some reason, the same document parsed as YAML shows the right amount of GitLens entries, but when I switch over to treat it as Azure Pipelines, way too many entries get injected.
If there's a different way to solve this, I'm all for it! But this seemed to fix it properly in my local workspace settings, and I think it should be the default for GitLens users.
Thanks!
=> Make Azure Pipelines use document scope

src/git/models/commit.ts
The email address was being correctly manipulated for the lookup of the Gravatar from local cache, but when the call to Gravatar was made for one that wasn't in the local cache the email was not being run via `trim()` and `toLowerCase()`.
This has been causing the avatars to fail to show for valid accounts.
=> Gravartars not showing if email contained upper case characters

package.json, src/git/gitService.ts, src/views/nodes.ts, src/views/viewCommands.ts
Add `stageDirectory` and `unstageDirectory` commands to (un)stage entire folder in tree view
fixes #599
=> (un)stage directory

README.md, package.json, src/git/git.ts, src/ui/config.ts
I am working on a documentation project that I have made a spreadsheet planner for, and entering the ID of the latest commit touching a given feature is required. Since the project is on GitLab, and said Git host has 8-character-long commit abbreviations, I have gotten used to the 8-character length. However, while pasting the commit ID from GitLens, I was surprised to find that it was only 7, which also frustrated me. This PR aims to allow the user to change the length of the abbreviated commit SHA, and relieve the frustration caused by inconsistencies in abbreviated commit ID length across multiple Git clients/hosts/software.
=> [Fixes #608] Adds the option to change the length of the abbreviated commit SHA

src/system/array.ts, src/views/nodes/branchOrTagFolderNode.ts, src/views/nodes/folderNode.ts
This commit occurring with branch names which are parsable integers. 
They were always shown first in the list of branches (even if they are
not starred) because the chrome implementation does not respect the
insertion order for keys that happen to be parseable integers.
It fixes Issue #626.
=> Avoid using objects to implement Map

src/git/parsers/remoteParser.ts, src/git/remotes/azure-devops.ts, src/git/remotes/factory.ts, src/git/remotes/provider.ts, src/views/nodes/remoteNode.ts
This PR fixes the missing _git issue mentioned in #620 
But it _doesn't_ fix the issue cause by the following cloning URL which requires reformatting the domain. 
`<org>@vs-ssh.visualstudio.com:v3/<org>/<project>/<repo>`
About the linting, there's a warning but it's not introduced by this PR. 
```bash
WARNING: vscode-gitlens/src/vsls/host.ts:78:9 - Promises must be handled appropriately
```
=> Fixes #620: Add missing _git in Azure DevOps URLs.

CHANGELOG.md
Add reference links in CHANGELOG for releases so version number link shows changesets in the release, where tags available . Remove the square brackets around versions where tags not available.
Related issue is #617
No code changes.
=> Closes #617: Adds version links to CHANGELOG

package.json, src/config.ts, src/git/git.ts, src/git/gitService.ts, src/views/nodes/resultsFilesNode.ts, src/views/nodes/statusFilesNode.ts
Solves issue #670.
- specifies the -M{x}% parameter in git diff when comparing
- adds setting gitlens.views.compare.findRenames
- adds info about the settings in README.md
=> solve the issue #670 Configure similarity index for diffs

README.md
The PR adds dedicated `GitLens` aka.ms link to the Live Share badge in `readme.md`.
-- 
I thought this is a too small change to create an issue for it, please let me know if you think otherwise.
=> [Readme][VSLS Badge]: change aka.ms link

src/git/remotes/bitbucket-server.ts
recent versions of Bitbucket server (formerly Stash) introduce an extra /scm in the URL, compared to older versions.
If it's detected in the path it's removed, therefore should work with all versions of Bitbucket server.
Tested with BB v6.1.2
- [x ] I have followed the guidelines in the Contributing document
- [x ] My changes are based off of the `develop` branch
- [x ] My changes follow the coding style of this project
- [x ] My changes build without any errors or warnings
- [x ] My changes have been formatted and linted
- [x ] My changes include any required corresponding changes to the documentation
- [x ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x ] My changes have a descriptive commit message with a short title, including a …
=> Fixes #692 - make remote work with recent versions of Bitbucket Server

package.json, src/git/git.ts, src/git/gitService.ts, src/views/viewCommands.ts
A request for the option to prune a remote was made in #556 
There was some discussion as to the exact functionality that people wanted:
The main concern I believe was to simply prune the remote
There was also talk to remove any local branches tracking pruned remote branches, which I thought might be better for a feature separate from pruning, as it alters the local repo in a way most would not expect
**EDIT:** it was agreed upon in #556 that this feature should just prune the remote. A new issue to implement the second functionality was made at #817 
Also, I wasn't sure which icon to use, but thought that the `icon-branch.svg` fit the best. I can change this if people wish
To test this feature with my test gitlab repo, I did the following:
1 - create a new remote branch on gitlab, and …
=> Adds feature to prune remotes. Fixes #556

README.md
Fixes #822
Change setting from `workbench.colorCustomization` to `workbench.colorCustomizations`.
=> Fix typo of "workbench.colorCustomization"

src/avatars.ts
Partial fix for #281 - covers the `*@users.noreply.github.com` case.
The `users.noreply.github.com` domain comes from users
making use GitHub's 'email privacy' feature.
Since the noreply address doesn't accept email, a user can't link
their preferred Gravatar to this type of email address.
The upside is that this address is easily parseable into:
* (optional) Github User ID
* Github User Name
We can use either to create the associated avatar link
without actually having to do an additional request
against Github's user search API.
Example changes from "contributors" list of this repository:
->
=> Uses GitHub Avatar for GH 'noreply' email address

src/git/models/repository.ts
I try to fix issue #893. Branch names are quoted now, while merging:
`git merge "#test"`. Before the generated command called: `git merge "#test"` wich does nothing, as `#` works like a comment in bash.
=> Fixes #893 - unquoted branch names in merge

src/git/models/remote.ts, src/quickpicks/remotesQuickPick.ts
Usually I want to, for instance, copy the URL to a commit on the origin, even if I have other remotes from forks. This adds a sort to show the origin at the top of the remotes list by default.
=> Sorts origin to top when selecting remotes

CONTRIBUTING.md
Fixes link typo in contributing page (would lead to no issues, corrected to the correct issue tag).
=> Fix typo in contributing search tag link

.github/workflows/codeql.yml
https://github.com/eamodio/vscode-gitlens/pull/1013 put the CodeQL workflow in a nested directory, which means it doesn't run. This moves it to the top level on the `.github/workflows` directory, which will get it working.
=> Move CodeQL workflow file

src/views/nodes/branchTrackingStatusNode.ts
Adds missing whitespace in a branch "n commits behind" item tooltip.
Fixes #1072.
Before:
After:
=> Fixes #1072 - Add whitespace to tree item tooltip

src/git/git.ts
This is a PR for issue #866.
Modifies the `git show` command to add the `--textconv` flag. This allows Gitlens to be used with any file that needs to be ran through `.gitattributes` to make it usable.
Our main motivation is to be able to use gitlens with files encrypted by [git-crypt](https://github.com/AGWA/git-crypt) but this is a generic change that should work with any tools requiring `.gitattributes` usage.
=> Adds ''--textconv' to show to support .gitattributes.

package.json
Fixes regexp that causes warning. Checked other regexps in `package.json` and haven't found problems with them.
=> Fixes #1187 - adds missing escape in regexp

src/git/gitUri.ts
When UNC path is used for a repo the gitUri is formatted without the double slash.
The following example is from a repo on `//aesrocc/home/ROCCTEST`
```
gitlens://0cee44d/aesrocc/home/ROCCTEST/fldedit/invfe53gst.et?{"path":"//aesrocc/home/ROCCTEST/fldedit/invfe53gst.et","ref":"0cee44d88243c4180f17837d9adf3b43a231ead2","repoPath":"//aesrocc/home/ROCCTEST"}
\_____/   \_____/\__________________________________________/ \___________________________________________________________________________________________________________________________________________/ 
|        |            |                                                                                 |
scheme     authority       path                                                                 query   
```
The uri strips the …
=> Fixes #1045 - Take UNC path from query instead of uri

README.md, package.json, src/config.ts
Adds two options to modify the behaviour of the file annotations button:
- "gitlens.menus.annotations.behaviour" changes the behaviour between a menu (default) and a toggle button
- "gitlens.menus.annotations.toggleType" changes what is toggled when behaviour is set to toggle
I wasn't too sure of what to name the settings so if you can suggest more appropriate ones that would be great.
=> Closes #1165 - Adds options to modify file annotation button behaviour

src/quickpicks/remoteProviderPicker.ts
- GitLens Version: 11.1.0
Fix the url linked to the `gitlens.connectRemoteProvider` command.
So, clicking on the help link now will redirect and navigate to the anchor text (here [Remote Provider Integration Settings](https://github.com/eamodio/vscode-gitlens#remote-provider-integration-settings-) )
=> Fix url that redirect to the "connect to remote provider" documentation

src/git/remotes/azure-devops.ts
Fixes #1303 
Remove the encoding to prevent double encoding for Azure DevOps URLs, to avoid these URLs from being 404 URLs.
When we added encodeURI() wrappers in 545dc4aac1a745362cabc6ed808d7c608dbe4a34, this caused a double-encoding problem with Azure DevOps URLs.
The problem exists in two places:
1. The baseUrl. Azure DevOps allows us to create projects and repositories which include spaces. This results in the path (and the subsequent baseUrl) containing `%20`. After being run through encodeURI(), this was changed to `%2520` which resulted in a 404.
1. I've decoded the path, so that later down the workflow, when we encode the entire URL, we don't end up double-encoding
---
2. The file path. Azure DevOps deep links to a path were hard-coded to use `%2F` instead of the `/`. After being …
=> Fixes #1303: Fix remote URLs for Azure DevOps

CHANGELOG.md, README.md, package.json, src/commands.ts, src/commands/common.ts, src/commands/copyCurrentBranch.ts
- Registers a command to bind a command id under the namespace `gitlens.views.branches`
- Adds a command contribution to make it available in the Command Palette
- Registers an onCommand activationEvent
- Uses GitService and env to copy the name to clipboard
I love using GitLens and it works great when managing multiple repositories and multiple branches. Given the large number of branches in my repos, I would find it extremely convenient to have a command from the Command Palette that copies the name of the currently checked out branch. I do this so many times in a day in order to paste it in trackers and pull requests.
While this can be done using the copy command in the branchesView, it will save having to open that view and scroll through the hundreds of branches to find the one with …
=> Adds Feature for Copy Current Branch Name

src/git/gitService.ts
`fs.realpath.native` in NodeJS uses the Win32 API function `GetFinalPathNameByHandle()` on Windows hosts,
therefore a given path must follow the guidelines for Win32 API file functions.
Drive letters on Windows need to end on a backslash according to the Win32 File Naming Conventions (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)
Omitting the backslash results in Windows treating the remaining path components as a relative path starting from the current directory on the specified disk (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths)
I tested this implementation for several repositories on Windows 10 using:
=> Fixes #1045 - Correctly resolve mapped drive on Windows

src/git/models/branch.ts, src/git/models/tag.ts
Corrects the compare functions that use String#localeCompare.  Fixes #1357
=> Fixes #1357 Corrects the compare functions

README.md
Corrects "Toggle File Changes Annotations" to match actual command name which is "Toggle File Changes".
- [X ] I have followed the guidelines in the Contributing document
- [ X] My changes follow the coding style of this project
- [X ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
=> Correct "Toggle File Changes" command name in doc

src/git/remotes/azure-devops.ts
Currently, the Copy As -> Copy Remote File Url command for an Azure DevOps repo does not result in an URL that will open the file. This closes #1439
=> [fix] Fixes Azure DevOps link formats. Fixes #1439

package.json
Hi maintainers! I'm Ivan and I work at [Bison Trails](https://bisontrails.co/). We're doing an internal hackathon this week.
Our team loves vscode-gitlens, but it got flagged during a recent security review. Our team voted to use our hackathon time to patch vulnerabilities in our favorite OSS tools and specifically to try to get vscode-gitlens approved for usage within our organization. 
- version of trim-newlines dependency is forced to resolve to the safe, patched version of the package
These changes should improve vscode-gitlens's security posture. We identified these vulnerabilities using [Salus](https://github.com/coinbase/salus) and the [OSSF scorecard](https://github.com/ossf/scorecard). The specific issues I am hoping to address here are:
- Regular expression Denial of service …
=> Fixes #1562: fixes version of trim-newlines

package.json
Adds isFileSystemResource to when clauses. Closes #1583.
=> Adds isFileSystemResource to when clauses. Closes #1583.

src/git/search.ts
Fixes #1131
Before this change, it was assumed (in `searchMessageOperationRegex`) that only the text *before* the search operations can be a free-text term.
With this change, we look for the free-text term in two places:
* before the first search operation (if none - the entire search is free-text)
i.e:  `hello world author: abc def` is interpreted as `message:"hello world", author: "abc def"`
* after the first message value (respecting double-quotes) of the last search operation.
i.e:  `author: abc def hello world` is interpreted as `author: "abc", message: "def hello world"`
to get the same result as before with this format, the search should be: `author: "abc def" hello world`
(this rule only applies if there is no free-text at the start of the search)
=> Fixes #1131 - "Search Commits" allows free term at search end

src/extension.ts
fix for : https://github.com/eamodio/vscode-gitlens/issues/1609
=> Fixes #1609 execute context.globalState.setKeysForSync only if it exists

src/avatars.ts
ref #1511 
I tried to solve the problem that the avatar of the retina screen is very blurred, but I don't think I did well. 
I am not particularly familiar with vscode plugin development. I don't know how to judge whether the current screen is a retinal screen, at the same time, it is not sure whether directly doubling the size of the avatar will cause other problems. 
If I bring trouble to you, please forgive me. I really hope someone can help.
=> Fixes #1511: Double the size of the Avatar

src/git/remotes/azure-devops.ts
Closes #1486 Adds autolinks for merged Azure Devops PRs with default messages.
=> Add ADO PR autolinks based on merge message

src/commands/git/merge.ts
---
This change just adds '--no-ff --no-commit' option to merge command.  
I personally use it all the time to review the code.  
Merge without commit, see problems, reset.  
Issue for that #1178 was created some time ago, but it seems it did not get any traction.
=> Fixes #1178: adds '--no-ff --no-commit' option to merge

src/avatars.ts
Closes #1898 
Was able to alleviate the stale Gravatar issue by deleting '.jpg' in the `getAvatarUriFromGravatar()` function in `avatars.ts`.
Gravatar now updates faster, current avatar compared to issue's screenshot stale avatar.
=> Closes #1898 - Removing '.jpg' for less stale gravatar

src/git/remotes/bitbucket-server.ts
Fixes #1932
Makes pull request autolink case insensitive, so it also works with Bitbucket Server 7
Now matches both "pull request #<num>" and "Pull request #<num>"
=> Fixes #1932: Ignores case for pull request autolink in Bitbucket Server

CHANGELOG.md, package.json, src/config.ts, src/webviews/apps/rebase/rebase.html, src/webviews/apps/rebase/rebase.scss, src/webviews/apps/rebase/rebase.ts, src/webviews/rebase/protocol.ts, src/webviews/rebase/rebaseEditor.ts
Adds a toggle button to control the visual ordering of the commits in the interactive rebase editor
=> Fixes #1190 adds ordering toggle to rebase webview 

src/webviews/apps/settings/partials/dates.html, src/webviews/apps/welcome/welcome.html
In date & time format settings, the feedback for "Time format" reads "Example date" rather than "Example time". This PR fixes that typo.
=> Fixes #1998

src/git/remotes/gitlab.ts
GitLens uses legacy project routes for GitLab:
- `${projectURL}/branches`
- `${projectURL}/tree/${branch}`
- `${projectURL}/commit/${sha}`
- `${projectURL}/compare/${base}${notation}${compare}`
- `${projectURL}/blob/${ref}/${fileName}`
These routes are all deprecated and scheduled for removal. See these references:
- https://docs.gitlab.com/ee/development/routing.html#project-routes
- https://gitlab.com/gitlab-org/gitlab/-/issues/118849
- https://gitlab.com/gitlab-org/gitlab/-/issues/28848
This change replaces them with the following scoped routes:
- `${projectURL}/-/branches`
- `${projectURL}/-/tree/${branch}`
- `${projectURL}/-/commit/${sha}`
- `${projectURL}/-/compare/${base}${notation}${compare}`
- `${projectURL}/-/blob/${ref}/${fileName}`
Examples:
- …
=> Fixes #2021 - Use scoped routes for GitLab URLs

CHANGELOG.md, src/commands/git/rebase.ts
When using git commands from terminal, one may prefer to use terminal editors to edit commit messages. But when using VSCode, it's better to use VSCode to edit commit messages. Currently gitlens uses VSCode to edit commit messages for amend. However it uses git's global `core.editor` for 'reword' in rebase. This PR ensures the usage of VSCode as `core.editor` for rebase.
Closes #2084
=> Uses VSCode as core.editor for rebase

src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss
- Updated the import paths used in `GitLens` to consume our components to use `@gitkraken` instead of `@axosoft`.
- We need both changes merged:
- `GitLens` import changes. 
- `GitKrakenComponents` library. PR: https://github.com/gitkraken/GitKrakenComponents/pull/12
[GITLENS-271](https://gitkraken.atlassian.net/browse/GITLENS-271)
=> GITLENS-271 - Modify the name of the lib to point to "@gitkraken" (Gitlens side modifications)

src/env/node/git/localGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx
Addresses GITLENS-198: https://gitkraken.atlassian.net/browse/GITLENS-198
Important notes:
1. Our local git provider regex for forming summary and message of a stash can sometimes generate blank messages and summaries when the summary of the stash from the git log does not include a WIP section or a summary section. For example, on stashes created within GitKraken we often get a description like `On expand-graph-container:`. Running `stashSummaryRegex` on this yields an `onRef` group, but a blank `wip` group and a blank `summary` group which causes `getStash` to yield a blank summery and message for that stash commit. In this case, I updated the logic to default to `WIP on ${onRef}`.
2. The local git provider was not previously parsing or storing the parent of a stash commit. This logic …
=> GITLENS-198 Add support for stash nodes to the graph

package.json, src/config.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/appBase.ts, src/webviews/apps/shared/colors.ts, src/webviews/apps/shared/theme.ts
https://gitkraken.atlassian.net/browse/GITLENS-258
changes:
- add mechanism to update the graph colors when the theme is updated in vscode by using a mutation observer. This might be redundant with the current theme.js mutation observer for the gitlens app, but I think this application of it is different enough that justifies a separate instance
- gets the correct font colors
- calculates graph and ref mixed colors that originally was done in the theme compiler.
=> gitlens-258 graph colors

CHANGELOG.md, package.json, src/@types/vscode.git.d.ts, src/@types/vscode.git.enums.ts, src/git/gitProvider.ts, src/git/models/repository.ts
Closes #1550. Force-push was also not working for non-HEAD commits in branches view. To fix these, I had to update [git API from the VS Code repo](https://github.com/microsoft/vscode/blob/main/extensions/git/src/api/git.d.ts) as I needed `force` parameter for `repo.push`.
I was also experiencing 2 exceptions before any of my changes - one for circular reference, another for null pr. I have handled them as well.
=> Closes #1550 - allow force-push for non-HEAD commits and from commit widget

src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss
Part of an effort to clean up the graph styles. The graph component will start to use a minified version of the graph stylesheet and will cascade vscode/gitlens properties to the graph component better
edit: we removed the changes to sending custom property names over computed values.
associated graph component PR:
https://github.com/gitkraken/GitKrakenComponents/pull/29
=> Use minified css stylesheet and better cascade theme properties

src/webviews/apps/plus/graph/GraphWrapper.tsx
Right now, when users first open their graph, they end up using the minimum column widths since the component sends over widths of 0. In this PR, I set up a default column width size that'll adequately show more information in the graph than the minimum (by default the graph nodes are squashed into a single column).
Future work includes auto-sizing the columns, but seems like this is a good fix for now.
testing:
In order to clear your current storage, you can add this line
`void this.container.storage.deleteWorkspace(WorkspaceStorageKeys.GraphColumns);` to the getConfig function in graphWebview.ts and opened the graph. 
Jira task: https://gitkraken.atlassian.net/browse/GITLENS-298
=> Graph: Use default column widths

CHANGELOG.md, package.json
Fixes https://github.com/gitkraken/vscode-gitlens/issues/2187
This PR adds a condition to the `scm/title` commands to target only the Git SCM provider.
=> Remove scm/title actions from non-Git scm providers

src/env/node/git/localGitProvider.ts
In the local git provider, we skip over HEAD in tips. This causes it not to populate in a commit row's Heads collection and therefore the graph doesn't display it when you're on a detached head. This change causes the detached HEAD to be added as a ref, so it makes it to the graph rows and ultimately is displayed as a local ref in the graph:
**Note:** In GK Client, we display the detached HEAD as a tag, rather than a local ref. I'm not sure why, but if we wish to do it that way, I can modify the logic here accordingly.  We would need to update the component-side graph logic in that case because Tag types don't include an "isCurrentHeadRef" property.
=> Send detached HEAD to graph

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/settings/partials/commit-graph.html
- Added two new input properties to the `GraphContainer` component:
- `highlightRowsOnRefHover`: boolean to enable/disable feature to highlight the rows on ref hover.
- `enableGhostRefs`: boolean to enable/disable feature to show ghost refs when hovering a row.
- Added property `enableGhostRefs` in the gitlens section settings: 
- Those changes works with PR: https://github.com/gitkraken/GitKrakenComponents/pull/80 
- I have noticed that once we change a setting in the Gitlens settings page, we have to close and reopen the graph to apply changes. I'm not sure if it's done that way on purpose. 
https://github.com/gitkraken/GitKrakenComponents/issues/73
=> 73 - Graph allow user to toggle some features in settings (Gitlens side)

src/webviews/apps/plus/graph/GraphWrapper.tsx
- Added the column header context on the column button.
https://github.com/gitkraken/vscode-gitlens/issues/2235
=> 2235 - REGRESSION: Once we hide columns of the graph using the new context menu, we cannot show them again

src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx
This PR attaches a "WIP" row to the top of the graph when there are changes in the working directory.
**Note:** To support this, I have utilized `git-ls-files`: https://git-scm.com/docs/git-ls-files/2.9.5
I also generated a new "work dir stats" model which represents the number of added, deleted and modified files.
**Additional notes:**
- We currently aren't sending the work dir stats into the graph as we cannot handle renames just yet. They are incredibly tricky to detect with unstaged files using git and it needs to be thought out more.
- We are using ls-files instead of diff shortstat because git diff does not pick up unstaged stuff by itself (which is a shame, because git diff DOES have rename detection).
=> Addition of Work In Progress row

package.json, src/env/node/git/localGitProvider.ts, src/git/models/branch.ts, src/git/models/graph.ts, src/plus/github/githubGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, yarn.lock
Sends PR metadata through to the graph in order to show PR icons next to refs when they are applicable.
Uses a dynamic system where an empty object is sent and remotes, when they render, ask for ref metadata. If we find something for them, we send it over. Otherwise, we send `null` indicating that this remote should stop asking for PR metadata.
To see PRs for a remote appear, you must connect to that remote first:
=> Send remote ids and handle ref metadata requests when remote connected

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/settings/partials/commit-graph.html
Requires component-side PR to merge first: https://github.com/gitkraken/GitKrakenComponents/pull/105
Note: Need to bump library version once that PR and this one are merged.
Adds a setting to show remote names on branches.
With the setting off (default):
With the setting on:
=> Add and send setting to graph for showing remote names on ref branches

src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx
- Used the `onDoubleClickGraphRef` input event property of the Graph component to do the check out of the branch.
https://user-images.githubusercontent.com/90025366/194901856-ec889122-34e9-42bf-9675-096ca55a45e4.mov
=> Graph: double-click on a ref to check it out (similar to GKC)

src/webviews/apps/plus/graph/GraphWrapper.tsx
Right now, Gitlens is calculating the `height` and `width` of the graph and passing its values via input properties to the component.
This calculation should be done internally in the Graph component instead (Graph component should be expanded to the container automatically).
That is, "height" and "width" input properties should be removed as they will no longer be needed.
- Removed logic to resize graph component (in `GraphWrapper.jsx` file) when webview is resized. Now, the graph component is able to do these calculations internally
- Removed `height` and `width` input properties of the `GraphContainer` component (in `GraphWrapper.jsx` file).
- This PR needs the changes of `Graph component` side as well: https://github.com/gitkraken/GitKrakenComponents/pull/117
- Once we proceed to …
=> 116 - Remove "height" and "width" input properties of the "GraphContainer" (Gitlens side)

webpack.config.js
- Ability to debug our Graph code by adding a breakpoint.
- Modified `webpack.config` to enable inline-source-map and avoid using terser when we are in development mode.
- This works with commit `Enable GK Graph debug` of Graph component side.
https://github.com/gitkraken/vscode-gitlens/issues/2284
=> 2284 - Enable GK Graph debug

CHANGELOG.md, src/commands/git/push.ts, src/git/models/repository.ts, src/views/viewCommands.ts
From a non-current branch's BranchTrackingStatusNode, push button was not triggering "Push force" when it's supposed to. This PR fixes #2292.
=> Fixes #2292 - force-push to non-current branch

CHANGELOG.md, src/env/node/git/git.ts
Fixes #1549. Fetch was not working when local branch name differs from remote branch name. This PR fixes that.
=> Fixes #1549 - git fetch for different upstream branch name

CHANGELOG.md, package.json, src/commands/git/rebase.ts, src/config.ts, src/system/utils.ts, src/terminal.ts
Closes #2134.
When using git commands from terminal, one may prefer to use terminal editors to edit commit messages. But when using VS Code, it's better to use VS Code to edit the commit messages. This PR ensures the usage of VS Code as `core.editor` whenever a terminal command is used.
=> Uses VS Code as core.editor

CHANGELOG.md, README.md, src/annotations/lineAnnotationController.ts
Refs: #2346
In the case of multiple cursors (selections) in the same line, an annotation was created per selection, resulting in an odd experience. Filter out duplicated lines by the line number and commit sha (sha is a safety measure for the probably impossible case of 2 commits in the same line).
=> Fixes: #2346 - duplicated inline annotations

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/settings/partials/commit-graph.html
This is the GitLens-side changes needed for configurable graph scroll padding to work.
[Component-side PR here](https://github.com/gitkraken/GitKrakenComponents/pull/149).
**Note** Must immediately bump library version once this and the component-side changes are merged, or there will be issues with the changes to the graph ref when jumping to commits during commit search.
Adds configurable scroll padding to the graph. This option is shown in the graph options and allows you to configure the number of rows away from the edge before the graph starts to scroll.
**Caveat 1:** This padding is only applied when auto-scrolling to a row (when the graph needs to select and jump to a commit you chose from outside the graph itself, i.e. in the search) or using keyboard scrolling. This padding …
=> Add option to modify the scroll padding for the graph

src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx
- Added handler to use the new graph input property event to be able to save the column ordering.
- Modified `onColumnChange` to be able to be able to notify more than one column change at the same time.
https://user-images.githubusercontent.com/90025366/200541279-5fd219d5-b397-4248-b2e0-69fdd9c41b1f.mov
- Works with PR https://github.com/gitkraken/GitKrakenComponents/pull/138 (`Graph component` side). 
- Once we get both PR merged, we need to bump the graph library version (in `Gitlens` and `graph component` side).
https://github.com/gitkraken/GitKrakenComponents/issues/84
=> 84 - Graph: Allow column re-ordering (Gitlens side)

src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/webviewBase.ts
- Added new notification to know the VS Code window focus state. In that way, we can notify the graph component to disable the hover behavior of the refs when Gitlens loses the focus. 
- This PR works with Graph component side changes: https://github.com/gitkraken/GitKrakenComponents/pull/157
https://github.com/gitkraken/GitKrakenComponents/issues/153
=> 153 - Rows are grayed out fairly frequently when VSCode loses the focus (Gitlens side)

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/settings/partials/commit-graph.html
Adds a graph setting for always dimming merge commit rows on the commit graph. Defaulted to off.
=> Add graph setting for auto-dimming merge commit rows

package.json, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/settings/partials/commit-graph.html
Adds the option to "dim merge commit rows", which is already in graph settings, to the filter dropdown for easier access/toggling.
Notes/questions:
- Removed "always" from the wording on the setting.
- Going through the command system to do this, would love feedback if there's a simpler way to set it up.
- Having this item checked activates the indicator on the filter icon, just like having any other item in that dropdown checked. Not sure if we want this, as this is technically not a "filter" in the same sense as the other options.
=> Add "dim merge commit rows" to filter dropdown

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/settings/partials/commit-graph.html
Adds a graph setting (default: off) to show stats on local branch refs in the graph relative to upstream when an upstream exists. These can be fetched dynamically (they use the same system as avatars).
=> Graph: add setting to show status of local branch relative to its upstream

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/settings/partials/commit-graph.html, yarn.lock
We had a setting to enable/disable upstream status for local branches in the graph. This adds a setting to toggle the other metadata type: Pull Requests.
This also combines all the active metadata from settings into a single array to send to the graph. This requires a graph library update after the breaking change lands: https://github.com/gitkraken/GitKrakenComponents/pull/189
Once that merges, the dependency will be updated in this PR and it can leave draft state.
=> Add setting to toggle PR icons in Graph

package.json, src/plus/webviews/graph/graphWebview.ts
Closes: #2419 
Adds three context menu options to work-in-progress row on graph to stash changes, open in commit details, and open SCM:
=> App context menu opens to WIP row on graph

package.json, src/plus/webviews/graph/graphWebview.ts, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, yarn.lock
Adds support for the new activity column in the commit graph. Allows the column to be toggled, and sends over colors for the bar visuals in the column.
**Note:** The colors being sent over are hard-coded, until we decide what colors we want to send over and handle theming.
**Note 2:** This cannot be merged until its [dependency PR on the component side](https://github.com/gitkraken/GitKrakenComponents/pull/196) is merged, and the graph library version updated, at which point the PR can leave draft.
=> Graph: add support for activity column

src/storage.ts, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Expands the deep link service to include a prompt to add the repo using three options (open in current window, open in new window, add to workspace) when a matching repo is not found while resolving a deep link. When a repo is chosen, a notification will indicate that the repo is being opened to resolve the deep link, and can be cancelled.
Includes pending state storage and recall for when adding the repo requires a new instance of the deep link service to continue resolving the link (such as when opening in the current window).
=> Deep Linking: Prompt to add repo for deep link when no matching repos found

package.json, src/config.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx
This PR accomplishes the following:
- Updates the "always-on" markers for rich scrollbar and minimap to HEAD/Upstream, Current Selection, Search Results (Highlights)
- Updates the "default" markers on rich scrollbar and minimap to Local Branches/Stashes.
- Adds a new setting `gitlens.graph.experimental.minimap.additionalTypes` to set up additional markers for the minimap (default are Local Branches and Stashes, and Remote Branches and Tags are available as well).
- The setting is available in User Settings and updating it should immediately update the markers in the minimap to reflect the new settings.
=> Add settings for additional graph minimap marker types

src/git/actions/commit.ts
Ensures added files get opened when only comparison refs are passed.
=> Fixes #2527 shows added files for Open All Changes

src/commands/git/worktree.ts, src/git/gitProviderService.ts, src/git/models/repository.ts
Issue repro steps:
1. Turn the `gitlens.detectNestedRepositories` setting on
1. Using git command line, create a worktree in the `.git` folder of a repo
2. Open that worktree
4. Attempt to create a new worktree while inside that worktree
Expected: You are able to create a new wotkree
Actual: You get a missing repository error in the debug output.
=> Skips caching when getting main repo for worktree creation

CHANGELOG.md, README.md, src/constants.ts, src/git/models/repository.ts
Uses the core git fetch command instead of a command-line git fetch so VsCode will prompt the user for their username and password. Pull & push also use their corresponding core commands.
=> Fixes #1968, #1027 - Fetch-> fatal: could not read Username

package.json, src/env/node/git/localGitProvider.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/remote.ts, src/plus/github/githubGitProvider.ts, src/storage.ts
Fixes: #2495
- Stores a cache of repo visibility that lives longer than the per-session cache
- Adds commands to reset the cache, either for open repos or for all repos
=> 2495 Cannot use gitlens+ feature on public repo in some folders

README.md, package.json, src/commands.ts, src/commands/copyRelativePathToClipboard.ts, src/constants.ts
This change adds a `Copy Relative Path` item to the context menu and the command palette. This copies the relative path, of the active file in the editor, to the clipboard.
Fixes #969
=> Fixes #969 adds copy relative path to context menu

CHANGELOG.md, README.md, package.json
Fixes #2566 hide context menu in output panel
---
to fixed #2566, this change will hide context menu in output panel
=> Fixes #2566 hide context menu in output panel

package.json, src/env/node/git/localGitProvider.ts, src/plus/github/githubGitProvider.ts, yarn.lock
Small change which sends the ID of upstreams along with their name (previously we only sent the upstream name) to local branch refs in the graph, for this feature to work: https://github.com/gitkraken/GitKrakenComponents/pull/205
Once the dependency PR is merged, the graph library published, and the dependency updated here, this PR will leave draft and be ready for review.
=> Sends upstream id on a local branch ref to graph

package.json, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/storage.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, yarn.lock
Completes #2598
Adds a column header context menu option to toggle the graph column default/compact mode.
[Dependency PR](https://github.com/gitkraken/GitKrakenComponents/pull/207) should be merged before this leaves draft.
=> Add graph header context menu option to toggle mode

package.json, src/plus/webviews/graph/graphWebview.ts
Adds the ability to "Publish Branch" in the context menu for local branches in the graph without an upstream.
This feature already exists in the Branches view - simply adding similar functionality to the graph.
=> Graph: Add "publish branch" context item for local branches

CONTRIBUTING.md
When installing and attempting to run the project for the first time, a pop-up was shown by VSCode when trying to run "watch & run". The pop-up said
> The task 'npm: watch' cannot be tracked. Make sure to have a problem matcher defined.
I realized that I was missing [this extension](https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher) and thought it would be helpful to others to know in the future.
=> Updates to contribution docs to include extension info

package.json, src/plus/webviews/graph/graphWebview.ts, yarn.lock
This PR unlocks graph columns that were previously locked in so that you can rearrange them and hide them.
The unlocked columns include the Branch/Tag column. the Graph column, and the Commit Message column.
On the graph component side, these columns were unlocked so that they can be  rearranged. On GL side, added commands to the graph header to be able to hide/unhide these columns.
A few caveats:
- Hiding all columns puts the graph into a weird state, so I added a restriction on hide commands that hides the "hide column" option when it's the only visible column.
- To calculate this "only visible column" and add it to the header context, I had to narrow the settings loop to only consider the most recent names of the columns, as there were old column settings that were never cleaned up in …
=> Unlock all graph columns (for moving and hiding)

CHANGELOG.md, README.md, package.json, src/ai/openaiProvider.ts, src/config.ts
Adds a `gitlens.experimental.OpenAIModel` setting to specify the OpenAI model to use to generate commit messages when using the `GitLens: Generate Commit Message` command.
Fixes #2636
=> Adds experimental.OpenAIModel

package.json, src/plus/workspaces/models.ts, src/plus/workspaces/workspacesService.ts, src/views/nodes/repositoriesNode.ts, src/views/nodes/workspaceNode.ts, src/views/workspacesView.ts
- Workspace repo descriptors now have their workspaceId on them (further code improvements to come from this, several places we can remove workspace id as input)
- Fixed a bug with creating a workspace with no description (we now require it)
- For the "current window" repo list in the view, added the workspace name or first repo name as a description to the item
- Unified the code for matching and resolving repos from descriptors. We were doing it separately in many places.
- Unified the code for parsing the provider, owner and name from a remote.
- Unified the logic for adding repositories to a workspace. The same function is now called when creating a workspace or adding repos to it.
- Filters out repos already in a workspace when adding to it
- "add repo to workspace" is now "add repos …
=> Workspaces Polish

src/commands/showView.ts, src/plus/webviews/graph/graphWebview.ts
Completes #2728
Command args were being lost in the intermediary logic when parsing the "Show Graph" command and the graph is in a view (aka Panel Layout, rather than Editor Layout).
Updates the `showView` pre-execution and execution steps to send the args through (and in case it's an SCM node, pack the node into args since the graph logic will parse it again anyway).
=> 2728 Submodule commit graph will not open in the panel layout

package.json, src/constants.ts, src/views/workspacesView.ts
Adds a button to the title of the Workspaces View that takes you to the help link to learn more about workspaces.
=> Adds info button to Workspaces View title with link to help page

package.json, src/constants.ts, src/env/browser/pathMapping/workspacesWebPathMappingProvider.ts, src/env/node/pathMapping/repositoryLocalPathMappingProvider.ts, src/env/node/pathMapping/workspacesLocalPathMappingProvider.ts, src/plus/workspaces/models.ts, src/plus/workspaces/workspacesPathMappingProvider.ts, src/plus/workspaces/workspacesService.ts, src/views/nodes/workspaceNode.ts, src/views/viewDecorationProvider.ts, src/views/workspacesView.ts
Improves linkage between vscode and cloud workspaces:
- Command next to a GitKraken Workspace in the Workspaces View, previously labeled "open as vscode workspace", split out to several commands: "create vscode workspace". "open vscode workspace (new window)", and "open vscode workspace (current window)".
- When you create a vscode workspace, it saves the GK workspace id in that code workspace file's settings. It also saves the file path of that code-workspace file for that cloud workspace in `cloudWorkspaces.json` in the shared folder (i.e. C`:/Users/(user)/.gk`).
- This changes the command for this cloud workspace from "Create" to "open". From now on, using the command opens the existing workspace at that location.
- When you create the vscode workspace, you now also have the option to …
=> Improves linking between GK and Local Workspaces

README.md
Fixes #2791
While looking into the repo's readme I found that the contributors link was non functional. In my testing it would appear that removing the two emojis at the end of the contributors link allows the link to gain it's intended functionality while not changing anything else about the page.
=> Fixes #2791 changes to fix contributors link in readme

package.json, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, yarn.lock
- Removed graph header settings button from Gitlens as now the Graph component can display that button and we have exposed new input properties.
- This PR works with GK graph library side changes: https://github.com/gitkraken/GitKrakenComponents/pull/231
- Before merge this PR, we have to update the GK graph library version dependency.
[230](https://github.com/gitkraken/GitKrakenComponents/issues/230)
Internal task: `GK.3665`
=> Move from Gitlens to the library the columns settings button

CHANGELOG.md, README.md, src/env/node/git/shell.ts
Fixes #2823
Handles cases where stdout/stderr are `Buffer`s in the shell `run()` helper:
https://github.com/gitkraken/vscode-gitlens/blob/c20ff5131eeb4b663eb6e191b7de8dab06949a78/src/env/node/git/shell.ts#L248-L258
=> Fixes #2823 - Handle stdout/stderr Buffers in shell run()

src/constants.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/errors.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/branch.ts, src/git/models/reference.ts, src/git/models/repository.ts, src/plus/github/githubGitProvider.ts
Adds our own implementations of `pull` and `push` and puts them behind the `gitlens.experimental.nativeGit` flag.
=> Adds native Pull and Push implementations to experimental Native Git flag

package.json, src/plus/webviews/graph/graphWebview.ts, src/views/viewCommands.ts
"Reset Current Branch to Commit..." context menu option in the graph would previously only appear when you were over a commit, rather than a branch.
This tiny change allows the option to appear on the context menu of a branch label in the graph, and should reset to the commit that branch is pointing to.
=> Allows graph "reset to commit" context menu option on branch item

package.json, src/commands.ts, src/commands/openOnlyChangedFiles.ts, src/commands/quickCommand.steps.ts, src/commands/showOnlyChangedFiles.ts, src/constants.ts, src/git/actions/commit.ts, src/plus/webviews/graph/graphWebview.ts, src/quickpicks/items/commits.ts
The new command can be accessed via the GitLens Command Palette: `GitLens: Show Only Changed Files` or on the context menu of the graph WIP node.
It simply combines the "open changed files" and "close unchanged files" commands into a single command for convenience.
=> Adds a "show only changed files" command to command palette and graph

CHANGELOG.md, README.md, src/commands/quickCommand.buttons.ts, src/commands/quickCommand.steps.ts
Fixes #2641
Add "Show changes button" beside "Reveal in side Bar" while open "Show file history"
=> Fixes #2641 Support search and open file history change

src/git/gitProviderService.ts, src/uris/deepLinks/deepLinkService.ts
Fixes #2880
When opening a deep link to GitLens requires VS Code to open, the deep link service enters a race condition with the git provider service on repo discovery. If the deep link service starts checking for a repo match before the git provider service has had a chance to finish at least some form of repo discovery, you can get situations where the correct repo is already open in the workspace but the service doesn't know it exists, so it asks for the user to manually open it.
This workaround exposes the `isDiscoveringRepositories` promise that the git provider service was previously using internally, and simply has the deep link service wait for it when processing a link.
Ideally the git provider service would expose its repo discovery and workspace folder knowledge in a more …
=> 2880 Deep Link Bug: When opening vscode as a part of a deep link, sometimes it asks to manually open a repo even if it's already open

src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Fixes #2891
Previously, the deep link service was not leveraging the repo path mapping file, so when you choose a location of a repo it is not saved to the mapping file, and when matching a repo for a deep link it does not try looking up the path in the mapping file.
In this PR:
- After choosing a location for a repo, it is saved to the mapping file for that remote url.
- When opening the deep link, we check the path mapping file if other forms of repo matching fail, and if matches are found, we show them in a quickpick and let the user either choose a path from the list or 'choose a different location' which reverts to manual choice.
=> Hooks deep link service into local repo path mapping

src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Fixes #2893
This PR achieves three main improvements to deep link processing for comparison links from PRs (using the web extension):
1. It now also considers the PR remote url in addition to the base url (the base url is the URL of the remote of the branch being merged, and the PR remote url is the url of the remote of the branch being merged into) for remote matching. If you are missing either remote, it offers the ability to add that remote.
2. It now supports branches that use the owner as the remote name. For example, if my branch name was `axosoft-ramint/main`, the matching branch may be `origin/main`. Previously we could not determine that this is the ref we really want; now it tries remote owner matching to resolve to the correct ref/sha.
3. We were doing a hacky workaround in the …
=> Improve comparison deep link processing from PRs

package.json, src/commands/base.ts, src/commands/copyDeepLink.ts, src/constants.ts, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts, src/views/viewBase.ts, src/views/workspacesView.ts
- Updates the base logic for views with a new internal fabricated event for when their children are fully loaded.
- Adds support for workspaces in the deep link processing flow. A workspace deep link is of the format:
1. GitLens: `vscode://eamodio.gitlens/link/workspace/<workspace id>`
2. GKDev: `https://gitkraken.dev/link/workspaces/<workspace id>`
- Adds share context menu item to workspaces with the ability to copy a deep link to the workspace to the clipboard.
=> Adds workspace deep link support

README.md, package.json, src/git/remotes/richRemoteProvider.ts, src/plus/subscription/subscriptionService.ts, src/plus/workspaces/workspacesService.ts, src/quickpicks/items/directive.ts, src/subscription.ts, src/webviews/apps/plus/account/components/account-content.ts, src/webviews/apps/plus/shared/components/feature-gate-plus-state.ts, src/webviews/apps/welcome/welcome.html
Updates the wording on licenses.
Please let me know if I missed anything, or changed something that shouldn't have changed.
=> Updates license strings

src/commands/showView.ts, src/plus/subscription/subscriptionService.ts, src/subscription.ts, src/webviews/apps/plus/account/account.scss, src/webviews/apps/plus/account/account.ts, src/webviews/apps/plus/account/components/account-content.ts
- Gets trial reactivation count from check-in response and stores on subscription plans.
- Updates messaging in the Account View body and statur bar hover to:
1. Include extra message on trial reactivation when detected.
2. Include a link to product page to align with GKC
- Updates status bar button click to open Account View rather than Home View.
=> Trial reactivation UX

package.json, src/env/node/git/localGitProvider.ts, src/plus/github/githubGitProvider.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/tsconfig.json, yarn.lock
- Added new property to format commit messages to be in sync with new changes of the `GK Graph`.
See task for more details: https://github.com/gitkraken/GitKrakenComponents/issues/303
- Works with dependant PR: https://github.com/gitkraken/GitKrakenComponents/pull/302
- For now, I left this PR as draft until changes related with the `GK Graph` are merged as we need to do a bump of that dependency in `GitLens` side.
=> Implemented new property of the GK Graph to format commit messages

src/webviews/apps/plus/graph/graph.scss
- https://github.com/gitkraken/GitKrakenComponents/issues/298
- The branch column header text disappears when you have a hidden ref.
- Adjusted CSS styles related with GK Graph headers.
- Those changes works with `GK Graph` PR: https://github.com/gitkraken/GitKrakenComponents/pull/299
- Changes are ready for review but I left this PR in draft mode as we need to bump the `GK Graph library` dependency version once above PR is merged.
=> [Regression] The branch column header text disappears when you have a hidden ref

package.json, src/commands/git/cherry-pick.ts, src/commands/git/merge.ts, src/commands/git/rebase.ts, src/commands/git/reset.ts, src/commands/git/revert.ts, src/constants.ts, src/env/node/git/localGitProvider.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/views/commitsView.ts, src/views/nodes/branchNode.ts
- Closes #1399 - Implements feature mentioned in https://github.com/eamodio/vscode-gitlens/issues/1399.
=> Closes #1399 - Adds option to filter out merge commits

CHANGELOG.md, README.md, package.json, src/config.ts, src/git/models/repository.ts, src/views/branchesView.ts, src/views/commitsView.ts, src/views/contributorsView.ts, src/views/nodes/abstract/repositoryFolderNode.ts, src/views/remotesView.ts, src/views/repositoriesView.ts, src/views/stashesView.ts, src/views/tagsView.ts, src/views/worktreesView.ts, src/webviews/apps/settings/partials/sorting.html, src/webviews/apps/settings/partials/views.branches.html, src/webviews/apps/settings/partials/views.contributors.html, src/webviews/apps/settings/partials/views.remotes.html, src/webviews/apps/settings/partials/views.repositories.html, src/webviews/apps/settings/partials/views.tags.html, src/webviews/apps/settings/settings.html
Adds an option to sort repositories in repositories view via name (asc/desc), last fetched (asc/desc), starred. Solves #2836 
https://github.com/gitkraken/vscode-gitlens/assets/65722512/dfbe455b-bfbf-48cc-bb0e-01ceff0c1777
=> Fixes #2836 adds sorting by repositories

CHANGELOG.md, src/commands/diffWithRevision.ts, src/commands/gitCommands.ts, src/commands/openFileAtRevision.ts, src/commands/openFileAtRevisionFrom.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/actions/commit.ts, src/git/fsProvider.ts, src/git/models/tree.ts, src/git/parsers/treeParser.ts, src/plus/integrations/providers/github/githubGitProvider.ts, src/quickpicks/commitPicker.ts, src/quickpicks/referencePicker.ts, src/quickpicks/revisionPicker.ts, src/system/path.ts
Fixes #708 - Prompt for file path when missing from revision
Improves the `openFileAtRevision()` function by:
- Asking user to enter another path when the requested file doesn't exist in the
selected revision.
- Showing an error message on subsequent failure (or if an error is thrown).
The above function is used by a number of commands:
- `gitlens.openFileRevision`
- `gitlens.openFileRevisionFrom`
- `gitlens.openRevisionFile`
=> Fixes #708 - Prompt for file path when missing from revision

package.json, src/config.ts, src/constants.ts, src/container.ts, src/plus/gk/account/organization.ts, src/plus/gk/account/organizationService.ts, src/plus/gk/account/subscription.ts, src/plus/gk/account/subscriptionService.ts, src/plus/gk/checkin.ts, src/plus/webviews/account/accountWebview.ts, src/plus/webviews/account/protocol.ts, src/webviews/apps/plus/account/account.ts, src/webviews/apps/plus/account/components/account-content.ts
- Adds a new service route for fetching GK organizations
- Adds an `activeOrganization` property to the active subscription in the Subscription service
- Adds a new command allowing the user to switch organizations (and, by extension, subscriptions)
- Adds new caches and storage for list of organizations, currently selected organization, and checkin response
- Adds new UX in the GitKraken Account view which shows the active organization and a button to switch
=> Adds organization switching

CHANGELOG.md, README.md, src/env/node/git/localGitProvider.ts
Simple follow-up fix to 095b469b4a752204bca7ea18a9314ba42aa6064e for #2926
Since remote refs can have a slash, this fixes cases where the selection revision came from a remote, e.g. `origin/release/5.0`.
Before:
After:
=> Replace all slashes in ref for git provider URI

CHANGELOG.md, README.md, src/trackers/gitLineTracker.ts, src/trackers/lineTracker.ts
Fixes #3066. See issue link for an in-depth explanation of the bug, steps to reproduce, and a video.
=> Fix indefinite line tracker suspension after closing large dirty editor

README.md, package.json, src/constants.ts, src/plus/gk/account/subscription.ts, src/plus/gk/account/subscriptionService.ts, src/plus/gk/checkin.ts, src/plus/integrations/providerIntegration.ts, src/plus/utils.ts, src/plus/workspaces/workspacesService.ts, src/quickpicks/items/directive.ts, src/system/date.ts, src/webviews/apps/plus/account/components/account-content.ts, src/webviews/apps/plus/focus/components/focus-app.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/shared/components/feature-gate-plus-state.ts, src/webviews/apps/plus/timeline/timeline.html, src/webviews/apps/shared/components/feature-gate-badge.ts, src/webviews/apps/shared/components/feature-gate.ts, src/webviews/apps/welcome/welcome.html
Adds trial reactivation command and UX when the user is considered eligible.
Updates plus feature gates and account view for this state.
=> Adds trial reactivation UX and command

CHANGELOG.md, package.json, src/commands/ghpr/openOrCreateWorktree.ts, src/commands/git/worktree.ts, src/config.ts, src/git/models/branch.ts, src/git/models/repository.ts, src/git/models/status.ts, src/plus/webviews/focus/focusWebview.ts, src/views/branchesView.ts, src/views/commitsView.ts, src/views/contributorsView.ts, src/views/nodes/abstract/repositoryFolderNode.ts, src/views/nodes/abstract/viewNode.ts, src/views/nodes/branchNode.ts, src/views/nodes/branchOrTagFolderNode.ts, src/views/nodes/branchesNode.ts, src/views/nodes/repositoryNode.ts, src/views/remotesView.ts, src/views/stashesView.ts, src/views/tagsView.ts, src/views/viewDecorationProvider.ts, src/views/worktreesView.ts
Adds a new `gitlens.views.collapseWorktreesWhenPossible` setting to change how we will try to show the opened worktrees (in a workspace) in many views  -- either as multiple repositories (default and existing behavior) or as a single (common) repository when possible.
Views currently affected: Branches, Remotes, Stashes, Tags, Worktrees, and Contributors (when showing all branches)
The Commit Graph & quickpicks are currently unaffected and should be addressed separately,
=> Adds ability to try to collapse worktrees in views

CHANGELOG.md, README.md, src/emojis.ts
Extend the `emojiRegex` to only `emojify` emojis that are delimited by a space (as in `"text :emoji: text"`), or with a line start / line end (as in `":emoji: text"` or `"text :emoji:"`)
(as a side note: i wanted to write a few tests to ensure this works, but i couldn't figure out where to place them so i just left it)
=> Fixes #3197 - Only emojify standalone emojis

CHANGELOG.md, src/system/color.ts, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/styles/theme.scss, src/webviews/apps/shared/theme.ts
This moves colors that can be generated using the CSS `color-mix()` function out of JavaScript code and back into CSS files. The remaining computed colors will require cross-browser support of CSS [Relative Color functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors) and will be updated in the future.
=> Optimizes theme color derivatives

package.json, src/cache.ts, src/git/models/pullRequest.ts, src/plus/focus/enrichmentService.ts, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/focus/focusProvider.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/github.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/jira.ts, src/plus/integrations/providers/models.ts, yarn.lock
Uses shared provider utility and its corresponding categories rather than our own.
Note: This requires querying github for additional properties we were not previously, in order to supply the library with all the information it needs on a PR to categorize properly.
=> Updates quick focus PR categorization

src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/focus/focusProvider.ts, src/plus/integrations/providers/github.ts
Previously, the quick focus and indicators would get into weird states if you're not connected to GitHub.
This PR addresses that as follows:
- New step in quick focus to confirm you have a supported integration connected, and offer ability to connect if not connected (GitHub only for now, but set to expand to new providers as added)
- New function in Focus Provider to check if a supported integration is connected (GitHub only for now)
- Updated state in Focus Indicator when not connected to GitHub, and a listener which updates the state when integration state changes. Includes a CTA link to connect to GitHub when disconnected.
- Special case logic in GitHub integration refresh to disconnect if we were disconnected in vscode (since our GH integration is controlled by vscode).
=> Makes Quick Focus and Indicators responsive to GitHub connection/disconnection

package.json, src/gk/models/drafts.ts, src/plus/drafts/draftsService.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/utils.ts, src/plus/repos/repositoryIdentityService.ts, yarn.lock
The `/v1/git-repositories/${repoId}` route in `RepositoryIdentityService.getRepositoryIdentity` is deprecated in favor of a route that directly associates it to a draft `/v1/drafts/${draftId}/git-repositories/${repoId}`. The `getRepositoryIdentity` method was moved to `DraftService` and now implements the new route.
The main difference in the `RepositoryIdentityService` functionality, besides removing that method, is that now the methods only interact with `RepositoryIdentityDescriptor` and no longer need to handle `GkRepositoryId`.
This converts issues and pull requests into a resource format that our APIs use to uniquely look them up.
Adds new params into DraftService.createDraft to support the `suggested_pr_change` type
=> Add features to DraftService

src/commands/gitCommands.ts, src/constants.ts, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/focus/focusProvider.ts, src/webviews/apps/home/home.html, src/webviews/apps/welcome/welcome.html
Adds some initial events and payloads relating to launchpad events.
Notes:
1. These payloads can be expanded if more data is needed.
2. We still need an event for "first-time" launchpad interaction. It still needs discussion and is TBD.
=> Adds initial launchpad telemetry

src/constants.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/jira.ts
Two events, one to track the first time a user's Jira integration is connected on a machine and the second to track every time a user opens the cloud integration settings on gkdev.
=> Adds initial cloud integration and Jira telemetry

src/system/command.ts
We call the constructor of all registrable events once when mapping them on extension load. This unfortunately causes the `launchpad/open` event to trigger, because we didn't include a `true` value for the `hidden` param in the constructor. This makes an exception for just that event in the mapping, so that the event doesn't trigger.
=> Fixes `launchpad/open` event always being sent on extension load

src/constants.ts, src/plus/focus/focus.ts
- Stores collapsed groups as a string array in global storage
- Updates this when a user toggles a group, but only when the launchpad wasn't opened to a specific group (when clicking a specific group from the launchpad indicator hover tooltip)
=> Saves collapsed groups on launchpad between uses

src/codelens/codeLensProvider.ts
Fixes Authors lens to say e.g. “one other” (in full “2 authors (Jane Doe and one other)”) when there are 2 authors (#3295).
=> Fix `GitCodeLensProvider.resolveGitAuthors…` "others" pluralization.

package.json, src/config.ts, src/env/node/git/localGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx
Closes #3313 - adds a new `Simply Merge History` filter option to the Commit Graph
=> Adds first parent toggle to Graph

package.json, src/git/models/commit.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/commitDetails/commitDetails.scss, src/webviews/apps/commitDetails/components/gl-status-nav.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/plus/graph/hover/graphHover.react.tsx, src/webviews/apps/plus/graph/hover/graphHover.ts, src/webviews/apps/plus/graph/hover/markdown.ts, src/webviews/apps/shared/base.scss, src/webviews/apps/shared/components/overlays/popover.ts, yarn.lock
Adds hovers to the Graph. This is still a work-in-progress and should probably be moved into the graph component itself.
See [GLVSC-524](https://gitkraken.atlassian.net/browse/GLVSC-524)
[GLVSC-524]: https://gitkraken.atlassian.net/browse/GLVSC-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds hovers to the Graph (wip)

CHANGELOG.md, src/plus/integrations/authentication/cloudIntegrationService.ts, src/plus/integrations/authentication/jira.ts
Looks like the docs indicate that you need to [send an access token in the body](https://dev-docs.gitkraken.dev/#tag/Provider-Connections/operation/post-v1-refresh-provider) for this request. I don't know if it's always been that way or if that's recent, but the route was previously working for us without doing this. We will need to update it (GLVSC-569)
=> Fixes the procedure of refreshing an access token in GK integration

src/commands/cloudIntegrations.ts, src/commands/remoteProviders.ts, src/constants.ts, src/container.ts, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/integrations/authentication/azureDevOps.ts, src/plus/integrations/authentication/bitbucket.ts, src/plus/integrations/authentication/github.ts, src/plus/integrations/authentication/gitlab.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/authentication/jira.ts, src/plus/integrations/authentication/models.ts, src/plus/integrations/integration.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/providersApi.ts
Introduces a provider for GitHub integration that tries to check for existing GitHub session before accessing an integration on GKDev (GLVSC-554)
=> Converts GitHub integration authentication to use gk.dev GLVSC-554

src/commands/remoteProviders.ts
Fixes the bug that the connect dialog appears twice for self-hosted integrations.
=> Don't make the second attempt to connect for non-cloud integrations (GLVSC-592)

CHANGELOG.md, package.json
Hide the action from command pallet GLVSC-586
=> Fixes open source controll action error

src/plus/focus/focusProvider.ts, src/plus/integrations/integration.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/github.ts
Silences error notifications from popping up from the Launchpad indicator's automatic "get my pull requests" query.
This is a workaround until we find a better way to present this issue to users when Launchpad runs into it.
Partially addresses #3367
=> Supress auth error notifications for github triggered by Launchpad

src/plus/gk/account/authenticationConnection.ts, src/plus/gk/account/authenticationProvider.ts, src/plus/gk/account/subscriptionService.ts, src/uris/uriService.ts
Adds support for links of the format: `vscode://eamodio.gitlens/login?code={code}(&state={state})`
These will login to the GK account using code-token exchange with the provided code/state.
=> Adds support for link to account login

CHANGELOG.md, src/plus/integrations/authentication/gitlab.ts, src/plus/integrations/providers/models.ts
In order to be able to merge Pull Requests in GitLab, we need to change the access token scope from `read_api` to `api`.
This PR changes the placeholder text when adding a new GitLab token, and also pre-fills the desired scopes through URL params.
Before:
After:
Pre-fill access token scopes via URL:
https://github.com/user-attachments/assets/757ea241-d8d7-415c-b120-e72ea7b4a4e8
=> Change GitLab access token scope (GLVSC-601)

CHANGELOG.md, src/git/remotes/azure-devops.ts, src/git/remotes/remoteProvider.ts, src/plus/drafts/draftsService.ts
Use remote.provider.owner as repoOwnerDomain
=> Fixes error when creating cloud patches for Azure repos

CHANGELOG.md, package.json, src/avatars.ts, src/commands/quickCommand.buttons.ts, src/git/models/author.ts, src/git/models/issue.ts, src/git/models/pullRequest.ts, src/plus/focus/enrichmentService.ts, src/plus/focus/focus.ts, src/plus/focus/focusProvider.ts, src/plus/integrations/integration.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/github.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/gitlab/gitlab.ts, src/plus/integrations/providers/gitlab/models.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/plus/integrations/providers/utils.ts, src/webviews/settings/settingsWebview.ts, yarn.lock
Shows Merge Requests on the Launchpad if GitLab rich integration is configured.
If both GitLab and GitHub are configured then shows PRs and MRs on the same list.
=> Launchpad: show GitLab PRs (and both GitLab+GitHub) [GLVSC-579]

CHANGELOG.md, src/plus/webviews/patchDetails/patchDetailsWebview.ts, src/webviews/apps/plus/patchDetails/components/gl-patch-create.ts
Disables `create {draftName}` button after first click
Then, enable if creation has been failed
https://github.com/user-attachments/assets/52a213d9-f221-4803-aa5f-a684b1684677
No need to reactivate the button if the creation is success
https://github.com/user-attachments/assets/9cbe32f4-c236-416a-b29b-fc7a1d5af5cf
=> Fixes multiple patch creation

src/commands/remoteProviders.ts, src/constants.ts, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/integration.ts
This is the solution of this issue: #3379 (GLVSC-591)
- Consolidates similar code to integration.connect call to hide that complexity
- Restricts the key params to be a subset of SecretKeys to avoid something else getting in there https://github.com/gitkraken/vscode-gitlens/blob/305d406cc7fe4247ad3cfae86cb860b87b4659ef/src/plus/integrations/authentication/integrationAuthentication.ts#L71-L96
- Replaces `Promise.all` and uses `Promose.allSettled` when we want to wait for everything
=> Consolidates similar code to integration.connect GLVSC-591

CHANGELOG.md, package.json, src/config.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/authentication/models.ts, src/plus/integrations/integrationService.ts
1. Get GitHub connection to GKDev active again
2. Hide it behind a config
3. Access local token before checking the remote
=> Enable GitHub authentication in gk.dev and hide it behind a config [GLVSC-618]

src/plus/gk/account/subscriptionService.ts
With this little change, we will validate the current subscription even if check-in fails or user is offline.
I tested this forcing a free account that expired yesterday into an offline client. In this case, GitLens checks if the stored license is valid even if it cannot check-in online to retrieve the latest information about the user's license.
=> Check subscription even if users cannot check in (GLVSC-593)

src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss
The drag event would get stuck if you kept dragging the resize handle outside the graph.
Creating a `mouseup` event when leaving the graph zone will release the resize event.
This behavior simulates what GKD does.
Before the fix:
https://github.com/user-attachments/assets/8716f315-5670-412d-9eed-f20280c7b049
After the fix:
https://github.com/user-attachments/assets/2aa228b5-8de3-4d64-ad03-0b7dc8f4c983
GKD's behavior:
https://github.com/user-attachments/assets/5a69d258-dfd5-4ff0-9505-a40096d48ee1
=> bugfix: Column resizing gets stuck when your mouse leaves the graph (GLVSC-610)

CHANGELOG.md, package.json, src/commands/git/cherry-pick.ts, src/commands/git/merge.ts, src/commands/git/rebase.ts, src/commands/quickCommand.steps.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/actions/commit.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/pullRequest.ts, src/git/models/reference.ts, src/plus/focus/focusProvider.ts, src/plus/integrations/providers/github/github.ts, src/plus/integrations/providers/github/githubGitProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/views/nodes/branchTrackingStatusNode.ts, src/views/nodes/compareBranchNode.ts, src/views/nodes/compareResultsNode.ts, src/views/nodes/pullRequestNode.ts, src/views/searchAndCompareView.ts, src/views/viewCommands.ts, src/webviews/commitDetails/commitDetailsWebview.ts
Adds comparison support for virtual repos
Improves merge & rebase commands
- messaging & count issues Improves comparisons with HEAD
- Splits into two commands: 1 for branches, 1 for others
- Commit/Stash/Tag command improves directionality based on topology and time Renames some comparison commands
=> Improves comparisons and adds virtual repo support

package.json, src/commands/openPullRequestOnRemote.ts, src/config.ts, src/constants.ts, src/container.ts, src/git/models/pullRequest.ts, src/plus/focus/focus.ts, src/plus/focus/focusProvider.ts, src/plus/integrations/providers/github/githubGitProvider.ts, src/plus/integrations/providers/models.ts, src/plus/repos/repositoryIdentityService.ts, src/system/iterable.ts, src/views/launchpadView.ts, src/views/nodes/abstract/viewNode.ts, src/views/nodes/pullRequestNode.ts, src/views/pullRequestView.ts, src/views/viewBase.ts, src/views/viewCommands.ts
Adds an experimental Launchpad view, behind a `gitlens.views.launchpad.enabled` setting. It has very basic PR functionality -- no specific launchpad actions, other than clicking on the row opens Launchpad
It also adds local repo matching and virtual repository fallback to show PR commits/files.
=> Adds Launchpad view (wip)

CHANGELOG.md, package.json, src/config.ts, src/plus/integrations/authentication/gitlab.ts, src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/authentication/models.ts
Checks for a local GitLab authentication and if it exists uses it.
Otherwise, it checks the GKDev for a GitLab integration to use it.
If GKDev is not connected it starts the GK authentication flow.
=> Modifies GitLab auth provider to use gk.dev (GLVSC-555)

package.json, src/config.ts, src/constants.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/branch.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/styles/shoelace/vscode-theme.scss
Replaces the branches filter toggle with a top-line dropdown and adds a new "smart" filter mode.
The "smart" mode which includes the current branch, the current branch's upstream (if any), and either the base branch or if current branch is associated with a PR then the PR's target branch.
Also adds a `gitlens.graph.branchesVisibility` setting to control the default behavior, though once you can it via the dropdown the change is remembered per-repo.
While I think this is in a reasonable state to merge, it can still be improved in future follow-ups:
=> Adds "smart" branches visibility

src/commands/gitCommands.ts, src/commands/quickCommand.ts, src/constants.ts, src/plus/focus/focus.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/models.ts
Adds support for using the new `/connect` page to connect cloud integrations.
Applies to the Launchpad "connect integrations" step when cloud integrations setting is enabled.
=> Adds new cloud integration connection flow and applies to Launchpad

src/constants.ts, src/git/models/branch.ts, src/plus/webviews/graph/graphWebview.ts
This is an improvement to the smart branch base/target detection. We now store target vs base separately, and favor target over base when available
=> Improves smart base/target branch detection

CHANGELOG.md, src/git/actions/commit.ts, src/webviews/apps/commitDetails/components/gl-commit-details.ts
- Adds menu for stashes on the commit graph from commits
- Makes localGitProvider.getCommitForFile return GitStashCommit | GitCommit | undefined
https://github.com/user-attachments/assets/41251127-1c76-487f-91be-1baf23952849
=> Adds menu for stashes on the commit graph

src/system/color.ts
make it possible to parse `hsl(100deg, 50%, 100%)`
=> Adds optional `deg` to cssColorRegex

src/plus/gk/account/authenticationConnection.ts, src/plus/gk/account/authenticationProvider.ts, src/plus/integrations/integrationService.ts
Fixes #3395
Two issues addressed here:
1. When initiating a login/register flow, if you hit cancel before opening gkdev, the completion input box still appears. It should not appear if you cancelled at this stage.
2. If the token input box appears, and then you hit `Escape` to cancel it, this should cancel the login flow. Right now, it does not cancel, and instead leaves it stuck, including processes that are waiting on it to complete.
To repro the second issue, log out of your account (both in GitLens and on gkdev), then click on the link under Autolink settings to "connect to Jira". Once you open the url, close out of it and then hide the code input with `Escape`. GitLens is now stuck waiting for that promise, so the next time you click the link it won't work, and if you try to reopen …
=> Prevents login flow from being stuck on cancel

src/commands/git/switch.ts, src/commands/git/worktree.ts, src/constants.ts, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Completes:  GLVSC-595
When we use "switch to" or "open worktree in new window" on a Launchpad item, and that action opens a new window (as a result of the "switch" operation), currently the last remaining part (open the inspect view, in review mode if appropriate) doesn't happen because the new window loses the deep link context.
This is tricky to fix, because the deep link service is not aware of the user's decision while it is awaiting the completion of the 'switch' command.
This solution addresses the issue as follows:
1. Expands the "stored deep link" to include a state representing where the link left off. Optional and if not provided, default is "repo opening".
2. Whenever the deep link needs to use the switch command, it first stores a pending deep link *just in case* a new window …
=> Stores and continues deep link flow when switch opens new window

src/env/node/git/localGitProvider.ts, src/git/models/worktree.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss
Note: requires graph-side PR to merge first.
After that, will bump the library version in this PR and remove it from draft.
=> Adds worktree id to refs and worktree icons to the graph

CHANGELOG.md, src/views/searchAndCompareView.ts
=> Doesn't reveal compare view on the `select to compare` action

src/plus/integrations/integration.ts
When you logout from GK Dev and then login back, all configured cloud integrations should become connected.
=> Fix connecting rich integrations on login to GK Dev (GLVSC-631)

package.json, src/commands/git/switch.ts, src/plus/focus/focusProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/views/viewCommands.ts
Adds the 'open in worktree' command to branches in views, prs in views (including launchpad view), and branches in the commit graph.
Note some restrictions:
- Is hidden for the current branch (attempting a switch there gives an error because it's your active worktree)
- Is hidden for branches that already have a worktree (there is already a command 'Open Worktree in New Window' that does the exact same thing)
=> Adds 'open in worktree' context menu command to branches and prs in views, and branches in graph

CHANGELOG.md, src/commands/git/worktree.ts, src/commands/quickCommand.steps.ts
Adds 2 new options to delete the branch as part of the worktree delete.
Which will after the completion of the worktree(s) delete, will start the delete branch(es) flow (at it confirmation step – which will naturally happen if all the context is provided to that flow)
=> Adds an option to delete a worktree along with its branch (GLVSC-637)

CHANGELOG.md, src/commands/git/branch.ts, src/commands/git/worktree.ts
Or instead, the Delete Worktree flow could just be triggered as an optional step in the Delete Branch flow.
=> Deleting a branch calls dialog of deleting its worktree (GLVSC-632)

src/plus/gk/account/authenticationProvider.ts, src/plus/gk/account/subscriptionService.ts
Currently we leverage the VS Code authentication system for our GK authentication, but this causes unnecessary prompts and limits our control over the experience.
We already implement both sides of the authentication process within GitLens, so we just need to avoid using VS Code as the middleman
- ❌ ~~probably stop implementing AuthenticationProvider~~ ➡️ probably but in a follow-up
- Be unauthenticated before the update:
- general behavior
- login
- restart VS Code: you should keep your session
- logout
- login again
- logout
- restart VS Code: you should keep being unauthenticated.
- integrations
- you're able to connect-disconnect rich GitHub integration,
- they survive restarting the application.
- disconect GitHub, then go to the Account View, press "Integrations" button, come back …
=> Change GK account authentication to no longer use the VS Code authentication system

package.json, src/commands/quickCommand.buttons.ts, src/commands/quickCommand.steps.ts, src/constants.telemetry.ts, src/constants.ts, src/container.ts, src/git/gitProviderService.ts, src/plus/focus/focus.ts, src/plus/focus/focusIndicator.ts, src/plus/gk/account/authenticationConnection.ts, src/plus/gk/account/authenticationProvider.ts, src/plus/gk/account/promos.ts, src/plus/gk/account/subscriptionService.ts, src/plus/integrations/integrationService.ts, src/quickpicks/items/directive.ts, src/webviews/apps/shared/components/promo.ts, src/webviews/apps/welcome/welcome.html
This still needs finalized messaging and promo testing.
=> Graduates Launchpad out of preview

src/commands/git/worktree.ts, src/git/models/worktree.ts
Closes #3542
Automatically chooses the `-b` flag or not based on if your chosen branch is already in a worktree.
Also, if the `-b` flag does apply, shows the "new branch name" prompt before the confirm step.
=> Refines 'Create Worktree' Flow

src/commands/git/branch.ts
It should just use the repo where you chose "create branch" from if you did it in branches view, graph, etc.. If you choose the wrong repo you get prompted for names etc. again
It has been found in https://github.com/gitkraken/vscode-gitlens/pull/3559
Details about reproducing are in this comment: https://github.com/gitkraken/vscode-gitlens/pull/3559#issuecomment-2346971475
=> 'Create Branch in Worktree' option in 'Create Branch' shows a repo picker if you have multiple repos open

.vscode/settings.json
Changes path to TypeScript SDK in settings to nix style, because otherwise VS Code on MacOS fails with detecting the right TypeScript path
Expected result: your VS Code understands the nix-style path to TypeScript SDK and the typescript version is detected as 5.6.0-beta
Undesired result:
- VS Code cannot understand the path, so it doesn't see the SDK in the project and switches to its ovn SDK, probably 5.5.4.
- In this case it shows errors in some files. For example in pull.ts (see on the picture)
=> Changes path to typescript sdk in settings to nix style

tests/e2e/playwright.config.ts, tests/e2e/specs/baseTest.ts, tests/e2e/specs/command_palette.test.ts
E2E tests were giving the following error:
This is caused because Playwright requires that parameter to be a destructured object, but our eslint rules collide with that because we don't allow empty patterns. The solution is to ignore that eslint line for this case.
In addition, I set the maximum timeout from 5s to 10s, as in some cases if VSCode takes too long to load, the test would timeout before even starting GitLens.
=> fix E2E tests

src/plus/integrations/authentication/integrationAuthentication.ts, src/plus/integrations/integration.ts
Fixes #3608
From the "sync cloud integrations" process we were setting "create if needed", which in `fetchOrCreateSession` will cause the gkdev connect flow to start (and website to open) if the session could not be fetched from the cloud.
This causes undesirable/unexpected UX for users, especially because it can happen from the background sync for cloud integrations, and can occur daily on each check-in.
In the case of #3608, the user had no local gitlab session, one existed in the cloud, but it was expired and could not be refreshed, causing the prompt to happen regularly on vscode launch or profile change.
This change adds a new `sync` flag to the `ensureSession`/`getSession` auth flow that acts as a softer version of `createIfNeeded`, and will not trigger a `connectCloudIntegration` …
=> Prevents cloud integration sync process from opening gkdev connect page/flow

CHANGELOG.md, src/commands/git/branch.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/repository.ts, src/plus/integrations/providers/github/githubGitProvider.ts
This is the first part of #3528 that changes `branch create` and `branch rename` into normal commands.
Since GitLens performs most of the validation for branch names, there wasn't really much to error check here.
Preparing next PR with `branch delete` which will probably contain more validations.
=> Change `branch create` and `branch rename` into normal commands

package.json, src/@types/global.d.ts, src/constants.commands.ts, src/constants.storage.ts, src/plus/gk/account/__debug__accountDebug.ts, src/plus/gk/account/subscriptionService.ts, src/plus/gk/checkin.ts, src/plus/gk/utils.ts, src/webviews/apps/shared/context.ts, webpack.config.mjs
Utility functions for debugging purposes only.
Also included in this PR are some fixes to types in the license response of check-in, since all license keys are not guaranteed to be in the response.
=> Adds debug commands and utilities to mock/restore subscription state

src/git/models/pullRequest.ts, src/plus/launchpad/launchpadProvider.ts, src/uris/deepLinks/deepLinkService.ts, src/views/viewCommands.ts
Closes #3627
Leverages `getOrOpenPullRequestRepository` to try to pre-identify the PR's repo, which then skips the "repo match" step in the deep link flow.
Note: this has undesirable effects with virtual repos, so I added a `skipVirtual` open to skip opening virtual uris for now. A bigger refactor of target opening logic (moving it out of the deep link service into its own service) will probably include better virtual repo support in the flow, but for now it doesn't work for most cases of `Open in Worktree`.
=> Attempts to pre-open PR branch when using Switch or Open in Worktree

src/constants.telemetry.ts, src/plus/integrations/authentication/cloudIntegrationService.ts, src/plus/integrations/authentication/integrationAuthentication.ts
Closes #3618
When doing a reauth with a cloud integration, disconnects the token from the backend before initiating a connect flow.
=> Completes the cloud integration reauth flow by disconnecting cloud token

CHANGELOG.md, package.json, src/commands/git/pull.ts, src/plus/webviews/graph/graphWebview.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/actions/fetchButton.tsx, src/webviews/apps/plus/graph/actions/gitActionsButtons.tsx, src/webviews/apps/plus/graph/actions/pushPullButton.tsx, src/webviews/apps/plus/graph/actions/syncButton.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/shared/components/menu/menu-item.ts, src/webviews/apps/shared/components/overlays/popover.ts
- add split button dropdown in case of both ahead and behind changes appeared
=> Adds a way to force push from the Graph

docs/telemetry-events.md, src/constants.telemetry.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/registration.ts, src/plus/webviews/patchDetails/patchDetailsWebview.ts, src/plus/webviews/patchDetails/registration.ts, src/plus/webviews/timeline/registration.ts, src/plus/webviews/timeline/timelineWebview.ts, src/system/object.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/plus/graph/sidebar/sidebar.ts, src/webviews/apps/plus/timeline/chart.ts, src/webviews/apps/shared/app.ts, src/webviews/apps/shared/appBase.ts, src/webviews/apps/shared/context.ts, src/webviews/apps/shared/telemetry.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/commitDetails/registration.ts, src/webviews/home/homeWebview.ts, src/webviews/home/registration.ts, src/webviews/protocol.ts, src/webviews/settings/registration.ts, src/webviews/settings/settingsWebview.ts, src/webviews/webviewController.ts, src/webviews/webviewProvider.ts, src/webviews/webviewsController.ts, src/webviews/welcome/registration.ts
- Adds new telemetry events for graph
- Adds new telemetry events for visual file history
- Adds `type` to the webview descriptor and used as a key in new `showAborted` and `shown` events
- Refactors `onShowing` hook to return a tuple which adds an optional context record that is mixed-in to the new `show*` events
- Adds telemetry context into the webview app and a low-level custom event handler
=> Adds graph and visual file history telemetry

src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts
Also puts draft items that need your review into the "needs your review" category, below non-draft items - closes #3654
Adds a draft icon to the detail section of draft items when they are not in the "draft" category, to the right of the "pinned" icon - closes #3655
=> Improves launchpad draft item UX

CHANGELOG.md, src/commands/git/worktree.ts, src/git/gitProviderService.ts
Fixes #3657
This needs some vetting of all the different worktree create options (default folder, choosing a new root, etc) to make sure it doesn't regress any behavior.
I also added an additional commit to honor a chosen root folder rather than always adding the "trailer" (e.g. `<repo>.worktrees` ) onto the root
=> Uses root repo path for worktree create

CHANGELOG.md, README.md, src/env/node/git/git.ts
There are cases for having bare clones with multiple worktrees in the same folder to manage various versions in a workspace
Currently, however, the only supported way to do this is to have the .git/ files such as HEAD, branches/, refs/, worktrees/, etc in the same folder as your actual worktrees. This makes your workspace very cluttered and is counterproductive to the structured way of multiple worktrees
What many of us prefer is to have an "empty" bare clone with the normal bare clone files within the .git/ folder or another folder labeled .bare and use a .git file with a gitdir reference
This fix will allow for the worktrees view to function the same way it would show on a `git worktree list` command
Refs: #3090, #2575
=> Fixes #3090 - Treats .git/gitdir as toplevel on "empty" bare clones

CHANGELOG.md, src/plus/launchpad/launchpad.ts
Fixes #3667
Here on screenshot you can see that "bbb" term is found in the author name but not in repository name. If I continue typing to "bbbchiv" nothing is found.
=> Fix launchpad search: make it search by repo name (#3667)

docs/links.md, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts
Closes #3677 and #3678
See changes in `links.md` for description of the new link type and supported values.
Example links to test with:
vscode://eamodio.gitlens/link/command/launchpad
vscode://eamodio.gitlens/link/command/walkthrough
=> Adds command deep links

src/constants.search.ts, src/constants.storage.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/graph/protocol.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.tsx, src/webviews/apps/shared/components/search/react.tsx, src/webviews/apps/shared/components/search/search-box.ts, src/webviews/apps/shared/components/search/search-input.ts
Having the button enabled allows you to filter when searching the graph.
Requires this PR merged as a pre-requisite, and dependency updated, before it can leave draft: https://github.com/gitkraken/GitKrakenComponents/pull/359
=> Adds filter button to graph search box

README.md
Update top section before Discover Powerful Features section since it's ready now before GL 16.
=> Top section update of readme before Discover Powerful Features section

src/commands/git/switch.ts, src/commands/git/worktree.ts, src/plus/launchpad/launchpadProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts, src/views/viewCommands.ts
https://github.com/user-attachments/assets/a4ebac45-b003-47de-9e44-4ad742b697b9
=> Opens all changes after open in worktree flow finished for PRs

CHANGELOG.md, docs/telemetry-events.md, src/constants.telemetry.ts, src/git/models/__tests__/pullRequest.test.ts, src/git/models/pullRequest.ts, src/plus/integrations/providers/github/github.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts, src/system/function.ts, src/system/vscode/asyncDebouncer.ts
When I copy and paste a PR URL directly into the input box on the main step, it should search for that PR
=> Search in Launchpad by PR URL. GitHub (#3543)

src/commands/git/tag.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/errors.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/repository.ts
Resolves #3529 
Here's what an error looks like now:
=> 3529 Change `tag` terminal-run commands into normal commands w/ proper error handling

docs/telemetry-events.md, src/constants.telemetry.ts, src/constants.ts, src/container.ts, src/telemetry/walkthroughStateProvider.ts
Two updates to note:
- Some completion events needed to check for a combination of both subscription state and shown/command usage
- Telemetry events now fire when that completion criteria is met
=> Adds telemetry for walkthrough completion

src/system/iterable.ts, src/webviews/apps/home/home.ts, src/webviews/apps/plus/home/components/branch-section.ts, src/webviews/apps/plus/home/components/branch-threshold-filter.ts, src/webviews/apps/plus/home/components/overview.ts, src/webviews/apps/plus/home/components/overviewState.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
https://github.com/user-attachments/assets/b08cbd71-bc86-400f-9e03-ccc61f8f2ad7
=> Adds threshold filter to the new home view

package.json, src/ai/aiProviderService.ts, src/ai/anthropicProvider.ts, src/ai/githubModelsProvider.ts, src/ai/huggingFaceProvider.ts, src/ai/openaiProvider.ts, src/ai/prompts.ts, src/ai/vscodeProvider.ts, src/ai/xaiProvider.ts, src/commands/generateCommitMessage.ts, src/config.ts, src/constants.ai.ts, src/constants.commands.ts, src/env/node/git/commitMessageProvider.ts, src/plus/webviews/graph/graphWebview.ts, src/plus/webviews/patchDetails/patchDetailsWebview.ts, src/plus/webviews/patchDetails/protocol.ts, src/system/string.ts, src/webviews/apps/commitDetails/components/commit-details-app.ts, src/webviews/apps/commitDetails/components/gl-commit-details.ts, src/webviews/apps/plus/patchDetails/components/gl-draft-details.ts, src/webviews/apps/plus/patchDetails/components/patch-details-app.ts, src/webviews/apps/plus/patchDetails/patchDetails.ts, src/webviews/apps/shared/styles/details-base.scss, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/commitDetails/protocol.ts
- Adds GitHub Models and Hugging Face support
- Adds latest model support from OpenAI, Anthropic, & Google
- Moves AI features from experimental to preview
- All-new settings for config and custom instructions Adds markdown output for AI explain
- Improves the AI explain prompting for better results
- UX changes to the Commit Graph WIP node
- Renames "Open Source Control" to "Commit via Source Control..." and moves it to the top
- Adds a "Generate Commit Message..." command under the above
=> Improves AI features

package.json
Added 10 experimental tags.
Added 29 preview tags.
=> Adds experimental tags to settings

src/system/webview.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-section.ts, src/webviews/home/homeWebview.ts
- handle push/pull actions
- add link to pr
- control force branches reloading
=> Fixes home view bugs

src/webviews/apps/home/components/preview-banner.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-section.ts, src/webviews/apps/plus/home/components/branch-threshold-filter.ts, src/webviews/apps/plus/home/components/launchpad.ts, src/webviews/apps/plus/home/components/overview.ts, src/webviews/apps/shared/components/button.ts, src/webviews/apps/shared/components/overlays/tooltip.ts, src/webviews/home/homeWebview.ts
- listening to git updates (push/pull/commit)
- add an indication of the async task is fetching
- fix gl-button click area in case of using tooltip prop
- add tooltip to the `publish branch` action
- fix promo banner dismissal
=> Fixes new home view bugs

docs/telemetry-events.md, package.json, pnpm-lock.yaml, src/commands/git/branch.ts, src/commands/quickWizard.ts, src/commands/quickWizard.utils.ts, src/constants.commands.ts, src/constants.telemetry.ts, src/git/models/__tests__/pullRequest.utils.test.ts, src/git/models/issue.ts, src/git/models/pullRequest.ts, src/git/models/pullRequest.utils.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/github.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/models.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts, src/plus/startWork/startWork.ts, src/webviews/apps/plus/home/components/launchpad.ts
This PR introduces initial Start Work flow that:
- adds a "Start Work" shortcut to the home view
- lets user to select a GitHub issue and then starts a create-branch flow
- suggests the repository of the selected issue as default repository for creating a branch
- suggests a default branch name based on issue title
=> PR on Start Work operation in Home view (#3621)

src/telemetry/walkthroughStateProvider.ts
=> Updates streamline collaboration usage triggers

src/webviews/apps/commitDetails/commitDetails.scss, src/webviews/apps/commitDetails/components/commit-action.css.ts, src/webviews/apps/home/home.scss, src/webviews/apps/plus/graph/graph.scss, src/webviews/apps/plus/patchDetails/patchDetails.scss, src/webviews/apps/plus/shared/components/home-account-content.ts, src/webviews/apps/plus/timeline/chart.scss, src/webviews/apps/plus/timeline/timeline.scss, src/webviews/apps/rebase/rebase.scss, src/webviews/apps/settings/settings.scss, src/webviews/apps/shared/base.scss, src/webviews/apps/shared/buttons.scss, src/webviews/apps/shared/components/accordion/accordion.ts, src/webviews/apps/shared/components/status/git-status.ts, src/webviews/apps/shared/popup.scss, src/webviews/apps/shared/snow.ts, src/webviews/apps/shared/styles/details-base.scss, src/webviews/apps/shared/styles/shoelace/vscode-theme.scss, src/webviews/apps/shared/styles/theme.scss, src/webviews/apps/shared/styles/utils.scss, src/webviews/apps/shared/utils.scss
- Consider `vscode-high-contrast` and `vscode-high-contrast-light` classnames in custom themed views
- Update some colors to make elements more visible in specific cases
https://github.com/user-attachments/assets/357be21f-d63b-4487-afe8-80ebecb2d6cd
=> Improves theme following on webviews

src/features.ts
Now we compare the elapsed time between an accepted range instead of plain dates.
=> fix: [Feature Preview] compare hours elapsed within range instead of dates

src/plus/startWork/startWork.ts
=> In Start Work switches to issue list before waiting for the result

src/webviews/apps/plus/home/components/branch-section.ts, src/webviews/apps/plus/home/components/overview.ts
https://github.com/user-attachments/assets/365d011c-740b-41ee-bade-e7c52dfdea5f
=> Adds no branches placeholder to keep the date filter always displayed

src/plus/startWork/startWork.ts
Stop hiding the quickpick when clicking the "globe" icon to open that issue in the browser (#3742)
=> Start Work: Stop hiding the quickpick when clicking the "globe" icon

CHANGELOG.md, package.json, src/commands/git/reset.ts, src/git/actions/repository.ts, src/plus/webviews/graph/graphWebview.ts
This PR introduces a new option in the Commit Graph context menu for resetting the current branch to a tag.
Solves #2373
=> Feat: Add context menu command to reset current branch to tag

docs/telemetry-events.md, src/commands/quickCommand.buttons.ts, src/constants.telemetry.ts, src/plus/startWork/startWork.ts
=> Shows different "globe" tooltips on GitHub and Jira issues in StartWork

src/commands/git/rebase.ts, src/commands/quickCommand.steps.ts, src/git/actions/repository.ts
Fixes #3747
Updates property names to be clearer in rebase command, and uses the correct side of the left-right commit count to:
1. Determine if the current branch is caught up to the destination
2. Determine how many commits will be rebased on top of the destination
Repro steps:
1. Choose a rebase command: "rebase current branch onto branch", "rebase current branch onto tip", or "GitLens: Git Rebase" command palette command.
2. Before: Quickpick prevents rebase and states that the current branch is already up-to-date with the destination when it is not. After: Quickpick should allow the rebase, and give the correct number of commits that will be rebased on top of the destination.
=> Uses correct counts in rebase command condition/messaging

CHANGELOG.md, package.json, src/autolinks/__tests__/autolinks.test.ts, src/autolinks/autolinks.ts, src/autolinks/index.ts, src/git/remotes/azure-devops.ts, src/git/remotes/bitbucket-server.ts, src/git/remotes/bitbucket.ts, src/git/remotes/custom.ts, src/git/remotes/gerrit.ts, src/git/remotes/gitea.ts, src/git/remotes/github.ts, src/git/remotes/gitlab.ts, src/git/remotes/google-source.ts, src/git/remotes/remoteProvider.ts
Adds getBranchAutolinks method to Autolinks class
Adds a few tests for autolinks
=> Add branchName autolinks

src/constants.commands.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-section.ts, src/webviews/home/homeWebview.ts
https://github.com/user-attachments/assets/2e14aaa2-550a-4aa7-b6d3-138d41c2844e
The thing I don't like is that for each action click a new compare node is created. Do we need to clear the nodes somehow or search duplicates before adding?
=> Opens multidiff view on open all changes from the home view

CHANGELOG.md, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/gitlab/gitlab.ts, src/plus/integrations/providers/models.ts, src/plus/startWork/startWork.ts
=> Shows GitLab issues in Start Work

package.json, src/config.ts, src/constants.commands.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/gitProviderService.ts, src/git/models/commit.ts, src/views/branchesView.ts, src/views/commitsView.ts, src/views/nodes/branchNode.ts, src/views/nodes/branchesNode.ts, src/views/nodes/remoteNode.ts, src/views/nodes/repositoryNode.ts, src/views/nodes/worktreeNode.ts, src/views/worktreesView.ts
I think this is ready for review/testing, as it works for any views that use "branch nodes", e.g. Commits, Branches, Worktrees, Repositories views. 
~~We will need to figure out how to get it to work with the Commit Graph without having to refresh all the commits (and stashes) based on the selected "Branches Visibility"~~
~~@axosoft-ramint maybe instead of filtering the stash commits, we just also return a set of "reachable" commits, and then be able to pass both sets into the Graph or something.~~
We will need to handle the Commit Graph differently.
=> Adds stashes into Commit view

src/plus/integrations/providers/jira.ts, src/plus/integrations/providers/providersApi.ts
Fixes current bug in which only 10 Jira issues maximum show up in Start Work (unable to create an issue due to a GitHub bug, will link the issue when I can create it).
There is an update to the shared provider library which increases the results per page from 10 to 100 - will look at bumping our library version as a separate task since there are some refactors needed to make it happy (and other risks that need to be tested).
=> Utilizes paging to get more Jira issues

src/plus/launchpad/launchpad.ts
Closes #3791
At some point along the way, we seem to have changed the "update items" logic in Launchpad to always force a full refresh of everything. For actions like pin, snooze, open on provider, merge, etc. we already have the provider bust the relevant cache so that only items that have changed are refreshed. So I changed the default behavior to use caches and only in a few places now do we force the full refresh.
Furthermore, to make pin/snooze/unpin/unsnooze even more optimistic, I created an `optimisticallyUpdateItems` function that just refreshes the list without having to do all the rest of the work.
These actions should be much more responsive now.
=> Restores optimistic behavior for Launchpad pin/snooze

contributions.json, package.json, src/config.ts, src/constants.commands.ts, src/git/gitProviderService.ts, src/git/models/branch.ts, src/git/models/remote.ts, src/git/models/repository.ts, src/git/utils/remote-utils.ts, src/system/paging.ts, src/views/branchesView.ts, src/views/nodes/branchNode.ts, src/views/nodes/branchesNode.ts
The setting is off by default.
Has some helpers that can be useful when adding the local/remote toggle to "recents" on Home
=> Adds ability to show the default remote branches in the Branches view

src/git/models/pullRequest.ts, src/git/models/pullRequest.utils.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/gitlab/models.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadIndicator.ts, src/plus/launchpad/launchpadProvider.ts, src/plus/launchpad/utils.ts, src/system/vscode/asyncDebouncer.ts
Closes #3855 
Current approach has some hacky workarounds to accommodate:
- Directly moving into search mode when a PR url is pasted in
- Not losing the content of the search box when toggling search mode on
- Showing the option to toggle search mode on if no results are found when searching with it off
Suggestions welcome
=> Updates Launchpad search UX to avoid always searching with the API

src/cache.ts, src/git/models/issue.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/github.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/jira.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts
Refines the issue model to be more supportive of Jira issues now that we're working with them more:
- Repository info on an issue would now be optional
- Adds optional project property with information on project and resource
Improves typing on resource descriptors in preparation for encoding them with a branch's associated issues in the git config
Adds getIssue and getProviderIssue to the base integration model, and implements for GitHub, GitLab and Jira. Updates provider API functionality to accommodate both GitLab and Jira.
=> Refines issue model and adds getIssue to supported integrations

src/autolinks/__tests__/autolinks.test.ts, src/autolinks/autolinks.ts, src/autolinks/autolinks.utils.ts, src/autolinks/index.ts
=> Fix autolinks tests: separate utils from UI dependent code

src/commands/git/branch.ts, src/constants.ts, src/git/models/branch.ts, src/git/models/branch.utils.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/utils.ts, src/plus/startWork/startWork.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-card.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
Closes #3870
In this PR:
- Adds models and util fns to get, add, remove or clear associated issues from branches in git config
- Plumbs git config associated issues through to the home view branch cards. Uses as primary source with autolinks as secondary source for associated branch issues
- Associates an issue with a branch when created through Start Work
- Deletes all issue associations in git config when a branch is deleted through our command
In the next PR:
- Split out issue list into its own command from Start Work
- Add a command to branches to "associate issue with branch"
=> Supports local issue association with branches

contributions.json, docs/telemetry-events.md, package.json, src/commands/quickWizard.ts, src/commands/quickWizard.utils.ts, src/constants.commands.ts, src/constants.telemetry.ts, src/plus/startWork/startWork.ts, src/plus/webviews/graph/graphWebview.ts, src/quickpicks/branchPicker.ts, src/views/viewCommands.ts
Closes #3884 
-Adds support for three commands:
- Command palette: Add Issue to Branch (you choose the branch after choosing the issue)
- Branch view items: Add Issue to Branch (associates the chosen issue with the existing branch)
- Graph branch items: Add Issue to Branch (associates the chosen issue with the existing branch)
=> Adds commands to Add Issue to Branch

src/plus/integrations/providers/jira.ts, src/system/vscode/storage.ts
Closes #3886
When we are about to store new Jira orgs with a session (and don't detect anything with that session with storage), we flush all existing global storage entries prefixed with `jira` to stop them from accummulating.
=> Flushes old Jira global storage entries on connect

src/webviews/webviewController.ts
=> Handles editor position change to refresh the webview

CHANGELOG.md, src/webviews/apps/plus/graph/GraphWrapper.tsx
=> Hides graph hover on context menu

CHANGELOG.md, src/webviews/apps/plus/graph/GraphWrapper.tsx
=> Adds go to home view button to the commit graph title section

CHANGELOG.md, ThirdPartyNotices.txt, package.json, pnpm-lock.yaml, src/env/node/pathMapping/repositoryLocalPathMappingProvider.ts, src/env/node/pathMapping/sharedGKDataFolder.ts, src/env/node/pathMapping/workspacesLocalPathMappingProvider.ts, tests/docker/Dockerfile, tests/docker/run-e2e-test-local.sh
All new installs files will be placed into platform specific folder
- Linux: $XDG_DATA_HOME/gk (~/.local/share/gk)
- Windows: %LOCALAPPDATA%/gk/Data (C:\Users\<user>\AppData\Local\gk\Data)
- MacOS: ~/Library/Application Support/gk
Existing installs are used $HOME\.gk directory. It can be changed manually by deleting .gk directory or moving to corresponding directory
https://github.com/sindresorhus/env-paths/tree/main could be used instead, it implements the logic
=> Makes GitLens XDG-compatible

src/commands/git/reset.ts, src/env/node/git/git.ts, src/env/node/git/localGitProvider.ts, src/git/actions/repository.ts, src/git/errors.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/repository.ts
This task creates the `git reset` commands to move away from `runTerminalCommand`. Solves #3533 
To be defined:
- Add those error cases where we want to recover from
=> 3533 Change `reset` terminal-run commands into normal commands w/ proper error handling

CHANGELOG.md, src/git/models/__tests__/pullRequest.utils.test.ts, src/git/models/pullRequest.ts, src/git/models/pullRequest.utils.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/__tests__/github.utils.test.ts, src/plus/integrations/providers/github/github.utils.ts, src/plus/integrations/providers/github/models.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/gitlab/__tests__/gitlab.utils.test.ts, src/plus/integrations/providers/gitlab/gitlab.ts, src/plus/integrations/providers/gitlab/gitlab.utils.ts, src/plus/integrations/providers/gitlab/models.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts, src/plus/launchpad/utils.ts
=> Search for GitLab PRs in Launchpad

CHANGELOG.md, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss
The additional dropdown is appeared only when not there are some branches hidden. It blinks twice after the first branch hiding, then it blinks one time per hidden branch. The dropdown is closed when the list is ended
https://github.com/user-attachments/assets/7937148e-c33c-494b-b84b-abdd1fd39590
=> Adds a new control for graph branches visibility

src/plus/integrations/integrationService.ts
(#3901)
This situation happens because an integration is cached twice with a real domain and with `undefined`:
=> Prevents caching a Cloud GitHub Enterprise integration without domain

src/git/remotes/remoteProvider.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/utils.ts, src/plus/launchpad/enrichmentService.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts
=> Supports GitHub Enterprise (GKDev) in Launchpad

src/container.ts, src/env/node/git/sub-providers/remotes.ts, src/git/parsers/remoteParser.ts, src/git/remotes/remoteProviders.ts, src/plus/drafts/draftsService.ts, src/plus/gk/utils/-webview/integrationAuthentication.utils.ts, src/plus/integrations/authentication/azureDevOps.ts, src/plus/integrations/authentication/bitbucket.ts, src/plus/integrations/authentication/configuredIntegrationService.ts, src/plus/integrations/authentication/github.ts, src/plus/integrations/authentication/gitlab.ts, src/plus/integrations/authentication/integrationAuthenticationProvider.ts, src/plus/integrations/authentication/integrationAuthenticationService.ts, src/plus/integrations/authentication/jira.ts, src/plus/integrations/authentication/models.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/github/sub-providers/remotes.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/webviews/home/homeWebview.ts
Major refactor (and fix to Home View integration states) that does the following:
- Creates a new configuredIntegrationService
- Moves all management of stored integration configurations as well as stored integration authentication sessions to the new service
- Renames functions across auth providers and the new service to be clearer, and simplifies logic on the integration authentication providers where possible
- Adds domain property to integration auth sessions
- Removes redundant code that isn't used, and makes a session descriptor required when interacting with an auth provider
- Updates home view to use the new service to get configured integrations
We will want this in before adding other cloud integrations into the mix, like Azure.
=> Moves configured integrations and session storage to new service

CHANGELOG.md, src/webviews/apps/home/components/onboarding.ts, src/webviews/apps/home/home.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/overview.ts, src/webviews/apps/plus/home/components/overviewState.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
- Splits home overview state by active and inactive branches
- Fixes unneeded overview refresh after opening the switch repo picker
- Fixes unneeded overview refresh when subscription data doesn't change
- Fixes repo file changes not reflecting while home that was made while home was hidden
=> Updates home overview - stale states and performance

src/commands/quickCommand.buttons.ts, src/constants.storage.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/utils.ts, src/plus/launchpad/enrichmentService.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts
Closes #3978
Adds Azure caching of account/projects/orgs and basic Launchpad support.
Note: avatar urls from azure are not publicly accessible, so they do not work for quickpick iconPaths. For now we are using the "account" codicon for anyone on an Azure PR until we find a better way.
=> Azure DevOps Integration Support - Add Launchpad Support

src/autolinks/autolinks.ts, src/container.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/azure/azure.ts, src/plus/integrations/providers/azure/models.ts, src/plus/integrations/providers/azureDevOps.ts
#3977 
An open issue
A closed issue
An open PR
A closed PR
=> Enriches Azure autolinks on commits: issues and pull requests

CHANGELOG.md, src/commands/git/rebase.ts, src/env/browser/platform.ts, src/env/node/git/git.ts, src/env/node/platform.ts, src/system/-webview/vscode.ts
Fixes #3952 - Avoids requiring shell integration for rebase
Closes #3969 - Adds Windsurf support and dyanmic support for other vscode-clones
=> Fixes #3952 and closes #3969

CHANGELOG.md, docs/telemetry-events.md, package.json, src/ai/aiProviderService.ts, src/ai/openAICompatibleProvider.ts, src/ai/prompts.ts, src/ai/vscodeProvider.ts, src/commands/git/stash.ts, src/commands/quickCommand.ts, src/commands/quickWizard.base.ts, src/config.ts, src/constants.telemetry.ts, src/plus/launchpad/launchpad.ts, src/plus/startWork/startWork.ts, src/system/function.ts, src/system/unifiedDisposable.ts
Closes https://github.com/gitkraken/vscode-gitlens/issues/4031
=> Adds AI-powered stash message generation support

CHANGELOG.md, docs/telemetry-events.md, src/ai/aiProviderService.ts, src/ai/vscodeProvider.ts, src/ai/xaiProvider.ts, src/commands/generateCommitMessage.ts, src/commands/git/stash.ts, src/commands/resets.ts, src/commands/switchAIModel.ts, src/constants.telemetry.ts, src/container.ts, src/env/node/git/commitMessageProvider.ts, src/git/utils/-webview/log.utils.ts, src/quickpicks/aiModelPicker.ts, src/views/viewCommands.ts, src/webviews/apps/home/stateProvider.ts, src/webviews/apps/plus/shared/components/integrations-chip.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts, src/webviews/plus/patchDetails/patchDetailsWebview.ts
=> Adds AI model status & picker to Home

contributions.json, package.json, src/constants.commands.generated.ts, src/constants.commands.ts, src/git/utils/-webview/pullRequest.utils.ts, src/plus/launchpad/launchpadProvider.ts, src/views/nodes/common.ts, src/views/nodes/pullRequestNode.ts, src/views/nodes/remoteNode.ts, src/views/viewCommands.ts, src/views/viewDecorationProvider.ts
Closes [#4039](https://github.com/gitkraken/vscode-gitlens/issues/4039)
Two fixes, each one commit:
- Fixes false "current branch" detection using the base repository ("current branch" and "remote" must use the head repository, but "open repo" can still use either)
- Instead of prompting, returns a command message node which can be clicked to add the missing remote.
=> 4039 Launchpad view can cause an unwanted "add remote" prompt on load

CHANGELOG.md, src/commands/quickCommand.buttons.ts, src/constants.storage.ts, src/plus/drafts/draftsService.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/plus/integrations/providers/bitbucket/models.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/plus/integrations/providers/utils.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts
solves #4046
The follow-up for improvement of the shared library: #4128
=> Bitbucket: Launchpad

CHANGELOG.md, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/plus/integrations/providers/bitbucket/models.ts, src/plus/integrations/providers/utils.ts, src/plus/startWork/startWork.ts, src/webviews/apps/plus/graph/GraphWrapper.tsx, src/webviews/apps/plus/graph/graph.scss, src/webviews/plus/graph/graphWebview.ts
solves #4047 
- Adds support for seeing Bitbucket issues in Start Work.
- Also makes sure Bitbucket issues can be associated to branches using the "associate issue to branch" command in branch context menus.
- Makes sure that the associated issue is displayed on Home
- Makes sure the associated issue is displayed on Graph
=> Bitbucket cloud: add Start Work support

CHANGELOG.md, src/git/remotes/bitbucket-server.ts
=> Fixes path splitting logic in BitbucketServerRemote

src/commands/git/switch.ts, src/commands/git/worktree.ts, src/constants.commands.ts, src/env/node/git/sub-providers/branches.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts, src/uris/deepLinks/deepLink.ts, src/uris/deepLinks/deepLinkService.ts, src/views/viewCommands.ts, src/webviews/apps/plus/home/components/branch-card.ts, src/webviews/apps/plus/home/components/merge-target-status.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts, src/webviews/plus/graph/graphWebview.ts
Closes #4124
Note: there are known issues with the "delete worktree" case where when the worktree is deleted before deleting the branch, the "delete branch" portion of the commands fail to proceed because the commands are using a worktree path that no longer exists. These should be addressed in follow-up.
=> Adds squash merge detection and merge target actions

src/plus/integrations/integrationService.ts
I've noticed that here the `connected` variable is always boolean and can never be equal to `null`, so we always skip the `if` body here: https://github.com/gitkraken/vscode-gitlens/blob/fef314b19051be1fd8890996e13091ef15c367da/src/git/gitProviderService.ts#L1143-L1149
Therefore, integrations with `unknown` connection status never get saved here: https://github.com/gitkraken/vscode-gitlens/blob/fef314b19051be1fd8890996e13091ef15c367da/src/git/gitProviderService.ts#L1191-L1194
As a result we don't see them on reading. For example in the List of Remotes it didn't see a connected Bitbucket integration and didn't request for PRs: https://github.com/gitkraken/vscode-gitlens/blob/fef314b19051be1fd8890996e13091ef15c367da/src/views/nodes/branchNode.ts#L178-L184
I've noticed that the related code …
=> Fixes isMaybeConnected to let it return undefined when the value is unknown

package.json, pnpm-lock.yaml, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts
- Integrates changes from https://github.com/gitkraken/provider-apis-package-js/pull/223
- Solves #4128
=> Extend the shared library to provide more data for bitbucket prs (and use it here)

CHANGELOG.md, docs/telemetry-events.md, src/constants.integrations.ts, src/constants.storage.ts, src/git/models/pullRequest.ts, src/git/remotes/remoteProviders.ts, src/plus/integrations/authentication/bitbucket.ts, src/plus/integrations/authentication/configuredIntegrationService.ts, src/plus/integrations/authentication/integrationAuthenticationProvider.ts, src/plus/integrations/authentication/integrationAuthenticationService.ts, src/plus/integrations/authentication/models.ts, src/plus/integrations/integrationService.ts, src/plus/integrations/providers/bitbucket-server.ts, src/plus/integrations/providers/bitbucket-server/models.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/plus/integrations/providers/utils.ts, src/plus/launchpad/enrichmentService.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadProvider.ts
=> Bitbucket Data Center cloud integration

contributions.json, docs/telemetry-events.md, package.json, src/constants.commands.generated.ts, src/constants.telemetry.ts, src/plus/gk/subscriptionService.ts, src/webviews/apps/plus/shared/components/account-chip.ts
Will need to be updated after https://github.com/gitkraken/vscode-gitlens/pull/4159 merges
=> Adds the referral program

CHANGELOG.md, package.json, src/commands/createPullRequestOnRemote.ts, src/config.ts, src/env/node/git/localGitProvider.ts, src/errors.ts, src/git/models/remoteResource.ts, src/git/remotes/azure-devops.ts, src/git/remotes/bitbucket-server.ts, src/git/remotes/bitbucket.ts, src/git/remotes/custom.ts, src/git/remotes/gerrit.ts, src/git/remotes/gitea.ts, src/git/remotes/github.ts, src/git/remotes/gitlab.ts, src/git/remotes/remoteProvider.ts, src/git/remotes/remoteProviders.ts, src/plus/integrations/integration.ts, src/plus/integrations/providers/azure/models.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/models.ts, src/plus/integrations/providers/providersApi.ts, src/plus/repos/repositoryIdentityService.ts, src/plus/workspaces/workspacesService.ts, src/quickpicks/remoteProviderPicker.ts, src/webviews/home/homeWebview.ts, src/webviews/plus/graph/graphWebview.ts, src/webviews/plus/graph/graphWebviewUtils.ts
=> Adds create pr urls for other providers

LICENSE.plus, docs/telemetry-events.md, src/commands/quickWizard.base.ts, src/commands/walkthroughs.ts, src/constants.telemetry.ts, src/plus/LICENSE.plus, src/plus/gk/__debug__accountDebug.ts, src/plus/gk/models/subscription.ts, src/plus/gk/subscriptionService.ts, src/plus/gk/utils/-webview/acount.utils.ts, src/plus/gk/utils/-webview/plus.utils.ts, src/plus/gk/utils/checkin.utils.ts, src/plus/gk/utils/subscription.utils.ts, src/webviews/apps/home/home.ts, src/webviews/apps/plus/LICENSE.plus, src/webviews/apps/plus/graph-next/graph-app.ts, src/webviews/apps/plus/graph-next/graph-wrapper/graph-wrapper.ts, src/webviews/apps/plus/home/components/merge-target-status.ts, src/webviews/apps/plus/shared/components/account-chip.ts, src/webviews/apps/plus/shared/components/chipStyles.ts, src/webviews/apps/plus/shared/components/feature-gate-plus-state.ts, src/webviews/apps/plus/shared/components/home-header.ts, src/webviews/apps/plus/shared/components/integrations-chip.ts, src/webviews/apps/shared/components/feature-badge.ts, src/webviews/apps/shared/components/promo.ts
=> Adds upgrade chip to home account button

CHANGELOG.md, docs/telemetry-events.md, package.json, src/api/gitlens.d.ts, src/commands/createPullRequestOnRemote.ts, src/config.ts, src/constants.telemetry.ts, src/env/node/git/sub-providers/diff.ts, src/extension.ts, src/features.ts, src/git/gitProvider.ts, src/git/gitProviderService.ts, src/git/models/remoteResource.ts, src/git/remotes/github.ts, src/git/remotes/gitlab.ts, src/git/remotes/remoteProvider.ts, src/git/utils/-webview/branch.utils.ts, src/plus/ai/aiProviderService.ts, src/plus/ai/models/model.ts, src/plus/ai/models/promptTemplates.ts, src/plus/ai/prompts.ts, src/plus/ai/utils/-webview/ai.utils.ts, src/plus/ai/utils/-webview/prompt.utils.ts, src/quickpicks/remoteProviderPicker.ts, src/webviews/apps/plus/home/components/branch-card.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
solves gitkraken/vscode-gitlens-private#43
=> Start Pull Request with AI

CHANGELOG.md, README.md, src/plus/integrations/providers/azure/azure.ts, src/plus/integrations/providers/azure/models.ts
This pull request resolves an issue where GitLens incorrectly links pull requests when a commit originates from a different Azure DevOps project, despite the commit tree being visible in the current project.
When a commit from a pull request (PR) in one Azure DevOps project (e.g., Project B) is reflected in another project (e.g., Project A) due to shared repositories or mirrored refs, GitLens correctly displays the commit in Project A. However, it incorrectly assumes the associated PR also exists in Project A, resulting in a broken or invalid PR link. Since PRs are scoped to their respective projects, this leads to a mismatch between the commit’s origin and the generated PR URL.
Fix includes using `pr.repository.project.name` when fetching the repository name, rather than just the current …
=> Fixes #4207 - Incorrect PR Link Across Azure DevOps Projects

eslint.config.mjs, package.json, pnpm-lock.yaml
Just quote from another PR: https://github.com/SocketDev/socket-cli/pull/386#issue-2948716252
=> chore: replace `resolver-oxc` with new `resolver-typescript`

src/git/parsers/remoteParser.ts, src/git/remotes/bitbucket-server.ts, src/git/remotes/custom.ts, src/git/remotes/github.ts, src/git/remotes/gitlab.ts, src/git/remotes/remoteProvider.ts, src/git/remotes/remoteProviders.ts, src/plus/drafts/draftsService.ts, src/plus/integrations/providers/bitbucket-server.ts, src/plus/integrations/providers/github/sub-providers/remotes.ts, src/plus/integrations/providers/providersApi.ts
=> Generates Bitbucket Data Center PR URL and retrieves repoId for cross-forks

CHANGELOG.md, src/cache.ts, src/plus/integrations/integration.ts
solves #4193
Adds `IssueOrPullRequestType` to cache keys for issue/PR retrieval preventing potential cache collisions.
=> Adds `IssueOrPullRequestType ` to cache keys for issue/PR retrieval

CHANGELOG.md, src/git/utils/pullRequest.utils.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/github/__tests__/github.utils.test.ts, src/plus/integrations/providers/github/github.utils.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/gitlab/__tests__/gitlab.utils.test.ts, src/plus/integrations/providers/gitlab/gitlab.utils.ts
follow up of #3923  and #3934
- Adds search by URL for GitLab Self Managed to the Launchpad
- Adds search by URL for GitHub Enterprise to the Launchpad
=> Searches by URL for self hosted GitHub and GitLab on Launchpad

src/constants.commands.ts, src/constants.storage.ts, src/git/models/repository.ts, src/uris/deepLinks/deepLinkService.ts, src/webviews/home/homeWebview.ts
https://github.com/gitkraken/vscode-gitlens/issues/4232
When using the "delete worktree" action on the merge target hover, closes the current window and hands the rest of the flow over to the existing window with the default worktree, whenever it exists already.
To make this happen:
1. Fixes a bug in `findCommonRepository` where we are passing a '.git' folder path into the lower-level rev-parse git ops, which ultimately results in an error from git (to repro in any terminal, navigate to the .git directory of a repo and try `git rev-parse --show-toplevel`. You will see a `fatal: this operation must be run in a work tree` error.)
2. Pending deep links are moved to secret storage so that GitLens in other windows can detect when they are stored externally.
3. A listener is added to the deep …
=> Improves handling of 'delete worktree' action on merge target when the default worktree is already open

CHANGELOG.md, docs/telemetry-events.md, package.json, src/config.ts, src/constants.ai.ts, src/plus/ai/aiProviderService.ts, src/plus/ai/ollamaProvider.ts, src/quickpicks/aiModelPicker.ts
Adds support for Ollama as a provider (requires Ollama server to be configured and running).
Prompts for URL when chosen or used as a provider and one is not configured.
Shows messaging when no models are installed.
To use:
1. Download Ollama: https://ollama.com/download
2. Install a model from the library: https://ollama.com/library (note: you can use any terminal and write, for example, `ollama run llama3.3` if Ollama is installed and configured)
3. Be sure Ollama is running, then use the "switch AI model" flow and choose Ollama, then put in your server URL (default is `http://localhost:11434` if you're running it locally.
4. Your installed models should show up in a list. Choose one and you're good to go.
Closes #3311
=> Adds Ollama support

CHANGELOG.md, contributions.json, docs/telemetry-events.md, package.json, src/commands/changeBranchMergeTarget.ts, src/commands/quickCommand.steps.ts, src/commands/quickWizard.ts, src/commands/quickWizard.utils.ts, src/constants.commands.generated.ts, src/constants.commands.ts, src/constants.telemetry.ts, src/constants.ts, src/env/node/git/sub-providers/branches.ts, src/git/gitProvider.ts, src/git/models/branch.ts, src/git/utils/-webview/branch.utils.ts, src/quickpicks/comparisonPicker.ts, src/quickpicks/items/directive.ts, src/webviews/apps/plus/home/components/merge-target-status.ts, src/webviews/home/homeWebview.ts
solves #4224 
Edit button and its tooltip:
Branch selection, filtered by:
- it's branch
- it's remote (does it have to be remote?)
Consequences: a new command has been added:
=> Allow the merge target to be changed or ignored

src/plus/integrations/providers/azure/azure.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/providersApi.ts
Fixes #4271
Forces the use of a PAT (and converts the token to PAT) on almost all shared library calls from Azure, except for `getCurrentUser` which does not support it.
Note that we may need to update local queries as well using the same logic.
=> Uses PAT on shared provider library requests from Azure

CHANGELOG.md, package.json, src/config.ts, src/git/remotes/azure-devops.ts, src/messages.ts, src/plus/integrations/providers/azure/azure.ts, src/plus/integrations/providers/azure/models.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket-server.ts, src/plus/integrations/providers/bitbucket-server/models.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/plus/integrations/providers/bitbucket/models.ts, src/plus/integrations/providers/models.ts
Implements `getPullRequestForCommit` and `getAccountForCommit` for Azure and Bitbucket.
Solves #4192
=> Implements `getPullRequestForCommit` and `getAccountForCommit` for Azure and Bitbucket

docs/telemetry-events.md, package.json, src/config.ts, src/constants.ai.ts, src/plus/ai/aiProviderService.ts, src/plus/ai/anthropicProvider.ts, src/plus/ai/deepSeekProvider.ts, src/plus/ai/geminiProvider.ts, src/plus/ai/githubModelsProvider.ts, src/plus/ai/gitkrakenProvider.ts, src/plus/ai/huggingFaceProvider.ts, src/plus/ai/ollamaProvider.ts, src/plus/ai/openAICompatibleProvider.ts, src/plus/ai/openAICompatibleProviderBase.ts, src/plus/ai/openRouterProvider.ts, src/plus/ai/openaiProvider.ts, src/plus/ai/utils/-webview/ai.utils.ts, src/plus/ai/xaiProvider.ts
Adds a new provider that mimics the OpenAI provider class with the difference being that a user-provider URL is required when configuring it.
Moves/renames the existing "OpenAICompatibleProvider" base class to "OpenAICompatibleProviderBase"
Closes #4263
=> Adds Open-AI compatible provider

src/plus/gk/subscriptionService.ts, src/plus/integrations/integrationService.ts
=> Make manual sync update sessions

docs/telemetry-events.md, src/constants.telemetry.ts, src/plus/integrations/integration.ts
It sends a telemetry events on on-usual token refreshing:
1. when we try to refresh a non-github token that does not have expiration date.
2. when we reject refreshing a token because we see that it's non-cloud token for a non-github integration
=> Send telemetry on unusual token refreshing

src/commands/git/branch.ts, src/commands/git/tag.ts, src/env/node/git/git.ts, src/env/node/git/sub-providers/branches.ts, src/env/node/git/sub-providers/tags.ts, src/git/errors.ts, src/git/gitProvider.ts
Refs: #3528
Replaces the terminal-based branch deletion approach with direct Git API calls that provide better error handling and user experience.
- Adds specific error types and reasons for branch operations including already exists, not fully merged, invalid names, and missing remote references
- Provides contextual error messages that help users understand what went wrong and why
- Shows confirmation dialog when attempting to delete unmerged branches, allowing users to force delete if desired
- Handles both local and remote branch deletions through the same interface
- Processes multiple branch deletions individually to avoid failing entire operations due to single branch issues
- Standardizes error handling patterns across branch and tag operations
- Adds dedicated methods for local …
=> Improves branch deletion by avoiding the use of the terminal

CHANGELOG.md, src/webviews/apps/plus/home/components/branch-card.ts
Resolves part of #4332.
- combines the "Create Pull Request" and "Create with AI" buttons into a split button
- adds the pull request icon to the primary button
- when the ✨ button is hovered, display the current tooltip: "Create a Pull Request with AI (Preview)"
=> Modify the "Create Pull Request" button

src/webviews/apps/plus/home/components/active-work.ts, src/webviews/apps/plus/home/components/branch-card.ts
part of #4332
- move the issue card above the branch card
- when no issue is associated, display an element with "Current work item" on the left and the issue icon to the right.
- when the issue icon is hovered, display a tooltip with "Associate an issue"
- when the issue icon is clicked, open the issue association flow
- when an issue is associated, display the issue card
- modify the current issue card to be shorter than the other cards (reduce the top/bottom padding to 4px from 8px)
=> Modify the issue association flow and Issue display

contributions.json, package.json, src/commands/generateRebase.ts, src/config.ts, src/constants.storage.ts, src/plus/ai/aiProviderService.ts, src/webviews/apps/home/stateProvider.ts, src/webviews/apps/plus/home/components/active-work.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
- **Updates feature labels** from "Experimental" to "Preview" across all AI commit generation and rebase functionality
- **Removes experimental configuration gates** that previously required explicit enablement of the two AI features
- **Adds one-time confirmation dialogs** to inform users about the impact of AI operations before execution (closes #4367)
The changes make AI commit generation and rebase features more accessible while ensuring users understand the implications of these operations through improved messaging and confirmation workflows.
=> Promotes AI features from experimental to preview status

src/env/node/git/sub-providers/stash.ts
Solves #4353.
The problem was in incorrect handling of blank "reachable stashes" result. In some cases the set of unreachable wasn't cleared so undesired stashes and commits appeared in the view.
=> Removes unreachable stashes from a branch when no reachable have found

src/commands/explainBranch.ts, src/commands/explainCommit.ts, src/commands/explainStash.ts, src/commands/explainWip.ts, src/commands/generateChangelog.ts, src/commands/generateCommitMessage.ts, src/commands/generateRebase.ts, src/commands/git/stash.ts, src/env/node/git/commitMessageProvider.ts, src/git/utils/-webview/pullRequest.utils.ts, src/plus/ai/aiProviderService.ts, src/webviews/commitDetails/commitDetailsWebview.ts, src/webviews/plus/patchDetails/patchDetailsWebview.ts
Fixes #4354 
- Modifies return output of `sendRequest` and callers up the chain to return (and handle) `'cancelled'` when a cancellation occurs.
- Returns without showing an error message on command-level logic when receiving `'cancelled'` as output.
=> Handles cancellation of AI commands

src/plus/gk/organizationService.ts
A follow-up on #4300 
- Fixes deleting of stored organization settings by _prefix_ on sign-out
- Deletes org settings from memory on sign-out, so when users signs in it takes fresh settings from GK.dev
- Refreshes org settings on manual refresh initialized by user (`onUserCheckedIn`).
=> Fix org sync cache on refresh and signout-signin

CHANGELOG.md, src/webviews/apps/plus/shared/components/integrations-chip.ts
Solves #4400 
- The label text is improved. It tells user to select AI provider and the model to start using AI feature
- The label text stopped being dimmed. It's shown with normal brightness
=> Improves AI label in the Integrations dropdown on the Home View 

scripts/esbuild.tests.mjs, src/commands/resets.ts, src/plus/gk/subscriptionService.ts, src/webviews/apps/home/components/ai-all-access-banner.ts, src/webviews/apps/shared/components/banner/banner.css.ts, src/webviews/apps/shared/components/banner/banner.ts
Fixes warnings like these:
```
▲ [WARNING] This case clause will never be evaluated because it duplicates an earlier case clause [duplicate-case]
src/webviews/plus/graph/graphWebview.utils.ts:173:7:
173 │     case 'github' satisfies Unbrand<GkProviderId>:
```
that started happening during `pnpm run test` here: f7faceae187a  (#4468)
Probably that started happening because `graphWebview.utils.ts` appeared in the test assembly for the first time, through a new chain of imports.
However, it does not appear on the main build task. Therefore I decided to modify building properties of tests, so the compiler become tolerant to these expressions as well as the main build.
---
Also fixes prettier that was broken in ff3858f191a9 (#4473)
=> Silences duplicate-case warnings in test builds

docs/telemetry-events.md, src/commands/aiFeedback.ts, src/constants.telemetry.ts, src/plus/ai/aiProviderService.ts, src/plus/ai/utils/-webview/ai.utils.ts
Fixes #4502
- Fills `type` field for `generate-rebase` AI event, so this field should stop being null in the feedback OTel events.
- Adds a new `feature` field. So events of `explain-changes` family have different features: `explain-branch`, `explain-commit`, `explain-stash`, `explain-wip`
=> Fills `type` and `feature` fields in AI feedback events

CHANGELOG.md, src/commands/aiFeedback.ts, src/commands/explainBase.ts, src/commands/explainBranch.ts, src/commands/explainCommit.ts, src/commands/explainStash.ts, src/commands/explainWip.ts, src/documents/markdown.ts, src/plus/ai/aiProviderService.ts, src/plus/ai/utils/-webview/ai.utils.ts, src/webviews/plus/patchDetails/patchDetailsWebview.ts
Solves #4328
- Updates AI provider methods to return the used model before the request is finished. The model is used to form partial document context.
- Stores partial context in URI that is enough to identify the document and to re-generate the content if it's needed.
- Stores the usage part of the context in memory that is used for sending feedback.
- Introduces a blinking hack to the `markdown.ts` in order to fight VSCode's caching of views (rewriting using the FileSystemProvider didn't help, but it can be reviewed here: 8c365a8fa5505826f8bd0eb781b4135116018ca1
=> Opens summary before AI result

docs/telemetry-events.md, src/commands/quickCommand.steps.ts, src/commands/walkthroughs.ts, src/constants.context.ts, src/constants.telemetry.ts, src/constants.ts, src/constants.walkthroughs.ts, src/container.ts, src/plus/gk/subscriptionService.ts, src/plus/launchpad/launchpad.ts, src/plus/launchpad/launchpadIndicator.ts, src/telemetry/walkthroughStateProvider.ts, src/webviews/apps/home/components/onboarding.ts, src/webviews/home/homeWebview.ts, src/webviews/home/protocol.ts
This brings back all the disabled Walkthrough actions for Cursor. Instead of trying to open the walkthrough, it will instead open a Help Center page.
=> Adds help center URL fallback for disabled walkthroughs

src/plus/integrations/providers/linear.ts
fixes #4621 (#4605)
Normalizes Linear autlink URL by removing summary stubs from its ending
Because it was cause of the duplication:
=> Fixes duplication of Linear issue links in the Inspect View

.gitignore, src/autolinks/autolinksProvider.ts, src/plus/integrations/models/integration.ts, src/plus/integrations/providers/azureDevOps.ts, src/plus/integrations/providers/bitbucket-server.ts, src/plus/integrations/providers/bitbucket.ts, src/plus/integrations/providers/github.ts, src/plus/integrations/providers/gitlab.ts, src/plus/integrations/providers/jira.ts, src/plus/integrations/providers/linear.ts
Unifies autolink enrichment keys for integrations in order to avoid referencing the exact integration type outside of integratin class.
Updates the autolink enrichment workflow to consistently use a pair of values (id and key) when resolving issues or pull requests across integrations. This removes provider-specific logic for constructing enrichment keys and centralizes the approach, simplifying maintenance and reducing errors when linking to external systems.
Renames and refactors relevant methods in integration classes to reflect this unified signature. Enhances consistency and clarity in how autolinked items are identified and retrieved across supported providers.
=> Unifies autolink enrichment keys for integrations

CHANGELOG.md, CONTRIBUTING.md, src/env/node/git/git.ts, src/plus/gk/__debug__accountDebug.ts, src/plus/integrations/authentication/cloudIntegrationService.ts, src/plus/integrations/providers/bitbucket/bitbucket.ts, src/system/-webview/asyncDebouncer.ts, src/system/color.ts, src/system/promise.ts
=> Fixes #4345 - fix typos
